### ISSUE TITLE
MCClans clan chat

### ISSUE THREAD

**Issue by PixelmonPRO** [Eufranio/MagiBridge#10]
Hello!
I use plugin MCClans, and Clan Chat messages go in global-discord-channel in Discord(
Use Nucleus, last version.

**Comment by Eufranio** [comment]
Hmm, I have to add support for MCClans. Will be fixed soon :)

**Comment by Eufranio** [comment]
@PixelmonPRO, are Clan and Ally the only private message channels of MCClans?

**Comment by PixelmonPRO** [comment]
@Eufranio I will not say exactly, I will test tomorrow.
It was noticed that the messages always through the command "/ cc message", do not come to the discord of the common channel. Only when the live chat mode is switched on "/ ss".

**Comment by PixelmonPRO** [comment]
@Eufranio Yes, Clan Chat and Clan Ally private only)

**Comment by Eufranio** [comment]
Thanks, will take a look on it soon.

**Comment by PixelmonPRO** [comment]
@Eufranio Test, clan chat and ally again go discord main and stuff channels (stuff channel go in /a, and /cc)
![2017-07-19_05 08 46](https://user-images.githubusercontent.com/26658563/28347621-dc119870-6c40-11e7-87dd-ee3cb4c7a4e0.png)
<img width="529" alt="screenshot at 19 05-09-23" src="https://user-images.githubusercontent.com/26658563/28347623-dfca9f52-6c40-11e7-81cc-2b2e214a2a3d.png">

**Comment by Eufranio** [comment]
How can I reproduce that? Are you on LATEST versions of both MagiBridge and MCClans? What chat hook are you using? Can you send your log? 

In a local test, I created a clan and ran **/cc hi**, and the message was not sent to Discord. Am I missing something?

**Comment by PixelmonPRO** [comment]
Laterest version MagiBridge) Laterest MCClans.
Command "/cc message" work good, not send message in discord, but player can run command:
"/cc" (switch clan chat), or ally "/clan chat ally"  - messages go in discord.

**Comment by Eufranio** [comment]
@PixelmonPRO, please test with [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.8.1-all.jar) and let me know if it's fixed.

**Comment by PixelmonPRO** [comment]
@Eufranio Test(
![2017-07-21_15 13 16](https://user-images.githubusercontent.com/26658563/28463121-84cbdb46-6e27-11e7-8663-82ce76042e8c.png)
<img width="525" alt="screenshot at 21 15-14-53" src="https://user-images.githubusercontent.com/26658563/28463128-8af4a476-6e27-11e7-8369-a9b2d12e95a6.png">
My config:
https://gist.github.com/PixelmonPRO/cfbfad10100a8988be05d62893f95d87

**Comment by Eufranio** [comment]
Are you sure you used [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.8.1-all.jar)? 
Can you send your plugin list?

**Comment by PixelmonPRO** [comment]
@Eufranio yes, used MagiBridge 1.8.1-all
<img width="616" alt="screenshot at 21 17-23-16" src="https://user-images.githubusercontent.com/26658563/28467688-5798041c-6e39-11e7-9208-61f62b5aaf08.png">
<img width="613" alt="screenshot at 21 17-23-32" src="https://user-images.githubusercontent.com/26658563/28467695-5b3264e6-6e39-11e7-8f45-d7fec7f89432.png">

**Comment by Eufranio** [comment]
Test on a local server with NO other plugins but MCClans, Nucleus and MagiBridge, and see if the issue still happening. 

If it does, you will have to test with your plugins and their config, and remove one by one until you find which one is causing it.
