### ISSUE TITLE
Topic updated was interrupted

### ISSUE THREAD

**Issue by XakepSDK** [Eufranio/MagiBridge#101]
I got this message while shutting down my server: [20:06:42] [MagiBridge Topic Updater/ERROR] [magibridge]: The topic updater was interrupted!
Nothing more, no exceptions.

**Comment by Eufranio** [comment]
That's expected: the topic updater is interrupted when you stop the server.

**Comment by XakepSDK** [comment]
Then maybe log this with `info` level? Also, topic wasn't changed to `server offline`.
