### ISSUE TITLE
Error message when not using staff chat

### ISSUE THREAD

**Issue by popcorn1111** [Eufranio/MagiBridge#102]
Our server does not send staffchat messages from Nucleus to the server discord, as we dont use it often enough for it to be important. However, since we dont use it, we get an "invalid channel error" everytime someone talks in the staffchat. This really clogs up the server console.

https://pastebin.com/7xgWnAPM

Can a "use-staff-chat" option be added to help prevent this? Or perhaps typing "DISABLE" as the channel ID? Anything to prevent the spam would be appreciated :)

**Comment by Eufranio** [comment]
Try with the latest version.
