### ISSUE TITLE
Unable to add more then 1 Ultimate Chat MC-Discord channels

### ISSUE THREAD

**Issue by ThornsOfire** [Eufranio/MagiBridge#104]
Versions: https://hastebin.com/ugapahehot

When adding more then one Ultimate Chat MC-Discord channels, after running "/sponge plugins reload" console throws an error then the magibridge.conf file internal contents are deleted.

Console Error: https://hastebin.com/idiniginup.sql

MagiBridge.conf with added channels (this file throws the error): https://hastebin.com/cucebabiru.coffeescript

**Comment by Eufranio** [comment]
Could you send the logs again? Looks like they were deleted (use gist, pastebin, etc).

**Comment by PoroUsedSnax** [comment]
I'm seeing this too, using MB 2.5 and UC 1.8.8.

The error I get from it is this: https://gist.github.com/PoroUsedSnax/9e2614de3b5c69484a4d45ec21e79249

The config I set up like so:
![config](https://i.gyazo.com/29befd7e8969586db2f444f1acfc6b2a.png)
I tried a few different ways but all errored (Having "" around each string, removing them entirely, comma after the first line)

I notice that when I reload after making the changes, the setup will work correctly but does delete the config as mentioned, so when reloading obviously it stops working entirely

**Comment by Asherslab** [comment]
@Eufranio i've had that issue before. it's because HOCON(?) is trying to convert the string number into an int, except that it's too long for an int (would need to be a long). I personally just told people to put a "#" infront of number and removed it myself.

**Comment by Hrubin2020** [comment]
You also should be able to put to an L at the end, to make it into a long

**Comment by Cavesnakes** [comment]
I have same issue exactly same as @PoroUsedSnax said

**Comment by Eufranio** [comment]
This is fixed in the new version of the plugin. Just add any non-numeric character to the channel ID in the config.
