### ISSUE TITLE
Links in Discord can't be clicked on ingame

### ISSUE THREAD

**Issue by Brycey92** [Eufranio/MagiBridge#107]
**Describe the bug**
If a link is pasted in the ingame chat channel on Discord, clicking the message ingame just takes you to the Discord invite page for our server.

**Expected behavior**
The invite link in the `[Discord]` prefix and pasted link in the message should be clickable separately.

**Comment by Eufranio** [comment]
Fixed in the latest MagiBridge version.

**Comment by Brycey92** [comment]
@Eufranio the issue has changed, but not been completely resolved. Now, the hover text and link for the invite only happens over `[Discord]`, which is the correct functionality for that, but links from discord messages aren't clickable ingame.
