### ISSUE TITLE
Bot's playing game by config

### ISSUE THREAD

**Issue by Animadoria** [Eufranio/MagiBridge#11]
It would be good an option on the config (or a command, idk) to change the bot playing state.

Like "playing %game%" or even transmiting.

**Comment by Eufranio** [comment]
Hey @Animadoria, could you test using the latest build from [here](https://github.com/Eufranio/MagiBridge/releases/tag/pre-1.8)?

**Comment by Animadoria** [comment]
Yes, it is working. Thanks
