### ISSUE TITLE
[Suggestion] Griefprevention softmute support

### ISSUE THREAD

**Issue by PoroUsedSnax** [Eufranio/MagiBridge#114]
[Griefprevention](https://forums.spongepowered.org/t/griefprevention-official-thread-1-10-1-11-1-12-town-wecui-support/1123) adds a softmute functionality where messages from those who are soft-muted don't get sent to the global chat of the server, but I guess to sort of a separate channel in which only soft-muted players can read each others messages (can be used for filtering out users who swear profusely, for example).

Currently though MagiBridge still sends these messages to Discord, it would be great to see this plugin respect that functionality.

**Comment by Eufranio** [comment]
Fixed in MagiBridge v2.6.
