### ISSUE TITLE
Topic Updater Log Spam

### ISSUE THREAD

**Issue by trabpukcip** [Eufranio/MagiBridge#118]
Issue #60 does not seem to be fixed.

I am using:
**SpongeForge:** spongeforge-1.12.2-2768-7.1.5-RC3513.jar
**MagiBridge:** MagiBridge-API7-2.5.jar

There must have been a brief Discord API outage earlier today and Magibridge could not find the required channel to update the topic.

I was getting the same error message as #60 describes:
`[MagiBridge Topic Updater/ERROR] [magibridge]: The main-discord-channel is INVALID, replace it with a valid one and restart the server!`

The logs have:
992969 occurrences of that string (each)
~4683 messages per second over 212 seconds
debug.log is 148MiB
latest.log is 140MiB

Fortunately the server is only in testing phase and was doing nothing, it also did not crash in this case.

**Comment by Eufranio** [comment]
Holy. I'll take a look soon.

**Comment by Eufranio** [comment]
Fixed with https://github.com/Eufranio/MagiBridge/commit/a92b9a84b2867c784c6f25ad759205b992bb0635.
