### ISSUE TITLE
Attachments & emoji conversion

### ISSUE THREAD

**Issue by fcpwiz** [Eufranio/MagiBridge#12]
- [x] 1. Discord attachments linked in MC (Show in mc as [Attachment] and the text would link to the file)

- [ ] 2. Change Discord emojis to text-based ones for the MC side of chat.

**Comment by Eufranio** [comment]
1. is already covered by #2
2. what do you mean? Not all discord emojis are known to the game language...

**Comment by fcpwiz** [comment]
@Eufranio 
1. Ah ok, I'll tell Sade66.
2. See this commit: https://github.com/axle2005/DiscordBridge/commit/ab463b5e72e01f722b3ec8b0aa37a62f3085c821

**Comment by Eufranio** [comment]
Hey @fcpwiz, could you test using the latest build from [here](https://github.com/Eufranio/MagiBridge/releases/tag/pre-1.8)?

**Comment by fcpwiz** [comment]
@Eufranio Dude, you're awesome! We'll test it out now!
