### ISSUE TITLE
2.6 does not fully instalize

### ISSUE THREAD

**Issue by Oshion01** [Eufranio/MagiBridge#120]
When server is loading with 2.6 it will say starting magibridge but that is all, then when I stop the server it will say stopping, thats all. 
Now if I roll back to 2.5 everything work the way it should. Thought I would let you know something is not quite right.

forge - latest
sponge - latest
server version 1.12.2

**Comment by Eufranio** [comment]
It's definitely working. Download it again and try, and if this doesn't work, send me your logs.

**Comment by MixxxmasterMac** [comment]
Same problem exactly, reverting to 2.5 fixed it for me too.
