### ISSUE TITLE
Response from server not sent to discord

### ISSUE THREAD

**Issue by krisjenner** [Eufranio/MagiBridge#122]
Executing commands from discord works fine but the response from server eg. "Pre generation is at 11.5%" doesn't come back through 

[error](https://gist.github.com/krisjenner/73c0dada5fae403c69ae708e6cbab5f2)

**Comment by Asherslab** [comment]
certain plugins respond to console differently than others, as such it's not possible to catch their responses (easily and through the appropriate means).

**Comment by krisjenner** [comment]
I understand that, but this happened after updating from 2.4.5.1 to 2.6 - reverting back to 2.4.5 and i get the messages back through to discord

**Comment by Eufranio** [comment]
Try with the new version.
