### ISSUE TITLE
!online message being deleted

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [Eufranio/MagiBridge#123]
Is this a feature of the plugin to auto-delete the !online message reply after like 5 seconds or so of being up because it's annoying and I can't find a configuration anywhere to disable it. It makes it very difficult in trying to find a player who is online.

**Comment by Meta-Win** [comment]
![image](https://user-images.githubusercontent.com/33970831/51858483-fa2f3e00-231b-11e9-9c63-48f1b13cbdbd.png)

**Comment by Eufranio** [comment]
As @Meta-Win showed, we have a config option for if magibridge should delete the player list message.
