### ISSUE TITLE
Console chat

### ISSUE THREAD

**Issue by JoshA20** [Eufranio/MagiBridge#124]
Not sure if this is right right location to suggest something, But here we go.

Will there ever be support to relay MC Console messages into a specified channel on discord? Sort of what DiscordSRV does at the moment. 

I think you should be able to see all messages that are view-able by console. I also think that you should be able to use commands in the discord channel, It'll then show up in the server

Cheers
Josh

**Comment by Eufranio** [comment]
I'm not sure how I can implement this, I'm open to suggestions.

**Comment by Asherslab** [comment]
i've got ideas on this. when i implement it in one of my services (if i do that is XD) i'll link it here (if i you haven't already gotten that done)

**Comment by daniel-widrick** [comment]
I've done something like this by wrapping the entire bot around the server.. Eg the discord bot launched the actual minecraft server and took control of the input/output pipes... We abandoned that whole process and went to sponge/this project.

That's probably out of scope for something relying on sponge apis.. Not sure though.

**Comment by Asherslab** [comment]
basically you can make a log4j filter 
and you can use that to get all the logging that goes to the console

**Comment by daniel-widrick** [comment]
interesting concept... Hadn't considered that... Make sure to check on any rate limiting discord may do... might cause some issues for the discord bot during startup because of flooding.

**Comment by Asherslab** [comment]
well with JDA it just makes the messages lag behind. so it shouldn't be an issue, other than it having to catch up

**Comment by corrompu-github** [comment]
Well... is a cool feature but having used DiscordSRV I can say is not perfect because if the server crash, the bot stop working and stop obviously to send console messages

**Comment by clienthax** [comment]
https://github.com/Eufranio/MagiBridge/pull/156

**Comment by Eufranio** [comment]
Please try with the new version.
