### ISSUE TITLE
Chat not being sent from Discord to Minecraft

### ISSUE THREAD

**Issue by Frogperson** [Eufranio/MagiBridge#125]
I'm trying to use vanilla chat (I don't have nucleus or ultimatechat) but messages are not being sent from discord to minecraft, only minecraft to discord works.

I have the default config but with a channel id, token, and "use-nucleus=" set to false.

Just some more that might help, if I set "use-nucleus=" to true (even though I don't have nucleus installed) my problem switches. Messages get sent from discord to minecraft, but not from minecraft to discord.

**Comment by Eufranio** [comment]
Will be in the next build.

**Comment by Eufranio** [comment]
Try with the new version.
