### ISSUE TITLE
Formatting bug?

### ISSUE THREAD

**Issue by Corcustos** [Eufranio/MagiBridge#127]
Not 100% what is causing this, but for whatever reason my server-to-discord and staff-to-server chat formats are presenting themselves very oddly.

Here is my config: [https://hastebin.com/onerutegok.coffeescriptt](https://hastebin.com/onerutegok.coffeescript)

Screenshots of what's happening for each setting: [https://imgur.com/a/vG3dHRD](https://imgur.com/a/vG3dHRD)

As you can see in the screenshot, some of the formatting is wrong for whatever reason. I want my server>discord chat to look the same as the staff server>discord. They have the same settings, but look different which really confuses me. Same goes for the discord>server chats.

Not entirely sure what to do to resolve this, any help is appreciated.

Versions:
Magibridge 2.6.1
Forge 2768
Sponge 3514
Nucleus 1.8.3

**Comment by Eufranio** [comment]
Set nucleus to not override the chat message of other plugins. Check it's config.

**Comment by Corcustos** [comment]
modify-main-message under the chat module is false. Is there another setting that I'm missing? I've tested all settings under the chat module and it's still happening.

**Comment by Corcustos** [comment]
@Eufranio
