### ISSUE TITLE
Error starting plugin

### ISSUE THREAD

**Issue by tonnic** [Eufranio/MagiBridge#128]
Not really sure what the issue is.... any way that I can debug?

10:52:40 AM CONSOLE: [ERROR] The Scheduler tried to run the task magibridge-S-2 owned by Plugin{id=magibridge, name=MagiBridge, version=2.6.1, description=A utility Discord <-> Minecraft chat relay plugin, authors=[Eufranio], source=./mods/MagiBridge-API7-2.6.1.jar}, but an error occured.

**Comment by Eufranio** [comment]
I need the rest of the error.

**Comment by tonnic** [comment]
Got it working... the discord admin gave me the wrong bot info.   Was
wondering, is there a chance you are going to update the mod?  I don't need
the discord link for any other feature (discord roles, etc.) but rather
would like to have them link their discord and then the ingame nickname
automatically changes their name to their discord name.

**Comment by Eufranio** [comment]
Then suggest it to MBDiscordLink.
