### ISSUE TITLE
Suggestion: Use helms instead of avatar in webhooks

### ISSUE THREAD

**Issue by kaal-1** [Eufranio/MagiBridge#13]
I see crafatar is being used to get the player heads that are used in the webhook. I think it would be better if helms were used instead, or maybe even enable a config option to customize the link to get the image from.

The implementation of this should be really easy, the only difference would be the added "&overlay=yes" in the end of the craftar link:
It would be:
https://crafatar.com/avatars/'+ player +'?default=MHF_Alex&overlay=yes

Another thing that would be great to see is an option to set the bot avatar from an URL.
See: https://github.com/Scarsz/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/commands/CommandSetPicture.java

**Comment by Eufranio** [comment]
You can change the bot picture by just clicking in the picture on the application page, there is no need to implement a command that does it.

**Comment by Eufranio** [comment]
@kaal-1, could you test with the latest build from [here](https://github.com/Eufranio/MagiBridge/releases/tag/pre-1.8)?

**Comment by kaal-1** [comment]
Yep! Works like a charm. Thank you.
