### ISSUE TITLE
Functionality Suggestion

### ISSUE THREAD

**Issue by Cosido** [Eufranio/MagiBridge#132]
Adding a Command Logging Functionality, which could be specified to send to a different channel in discord. 

It would send commands that a user has the permission node for.

Example:
magibridge.logger.mute
magibridge.logger.ban

Adding these to a group in a Permissions Manager, would direct any messages in minecraft(log) to a discord channel ID, Seperate from any current channels allowed in the config (A specific logging channel)

A user (Player) with the permission "magibridge.logger.ban" using the command "/ban Player2", would have the message "Player has banned Player2" sent to the specified logging channel.

This would allow for networks to easily preview punishment logs on the server, without manually inputting logs, or needing the access to FTP

**Comment by Asherslab** [comment]
If you have a developer for your server or etc. MagiBridge does have an API that can be attached to. (i only mention this because this addition may be outside the scope of MagiBridge)

**Comment by Eufranio** [comment]
I don't think this fits for the purpose of MagiBridge. As Asherslab said, you can use the API (that I just implemented) to do it.
