### ISSUE TITLE
%toprolecolor% não está funcionando para jogadores sem tag

### ISSUE THREAD

**Issue by Focamacho** [Eufranio/MagiBridge#133]
Em base está acontecendo isso para os jogadores que não possuem nenhuma tag no discord:
![image](https://user-images.githubusercontent.com/48870573/55252233-25a5aa80-5231-11e9-9ed1-64820e0e26cf.png)

Aqui está minha config de cores:
![image](https://user-images.githubusercontent.com/48870573/55252267-3e15c500-5231-11e9-9cec-bf15364ab2e6.png)

Config Discord-To-Server:
![image](https://user-images.githubusercontent.com/48870573/55252293-508ffe80-5231-11e9-9eb3-06c5592cde72.png)

**Comment by HeberonYT** [comment]
I have the same problem.
In discord I have different roles assigned with different colors.
But when writing, the code 99AAB5 is always sent to minecraft, regardless of the role assigned to the user.
In addition, I have placed a color (&9) to the code 99AAB5 but it is not replaced by the bot, something is not working here.

-MagiBridge-API7-2.6.2.jar
