### ISSUE TITLE
Sugestão: Players em Vanish

### ISSUE THREAD

**Issue by Focamacho** [Eufranio/MagiBridge#134]
Atualmente a quantia de jogadores online mostrada no tópico do canal se refere a qualquer jogador que esteja dentro do servidor, não importando se ele está em vanish ou não. Seria interessante ter alguma opção dentro das configs do plugin que nos desse a opção de esconder do total de jogadores online os players que estivessem em /v.

Vanish ativo:
![image](https://user-images.githubusercontent.com/48870573/55252909-b0d37000-5232-11e9-98ef-728d06fde364.png)

Comando !online:
![image](https://user-images.githubusercontent.com/48870573/55252935-bf218c00-5232-11e9-87d1-d9b9182f8f81.png)

Tópico do Canal: 
![image](https://user-images.githubusercontent.com/48870573/55252950-c9dc2100-5232-11e9-8516-16156b6d1234.png)

**Comment by Corcustos** [comment]
If this is suggesting that vanished players not be counted in the server count/etc I 100% support this. I came here to make that very suggestion and saw this. Players obviously know someone is vanished online if nucleus' /list has 1-2 lower playercount than magibridge's topic.

**Comment by Eufranio** [comment]
It seems to be fixed in the last Sponge version.
