### ISSUE TITLE
Player count in topic never updates

### ISSUE THREAD

**Issue by KarlOfDuty** [Eufranio/MagiBridge#140]
Picture taken with several players online after waiting a few minutes.

![image](https://user-images.githubusercontent.com/18099825/62908401-253d2480-bd78-11e9-9bbf-bbec37b070fd.png)

**Comment by BrandHyde** [comment]
Neither does mine, previous update breaks the whole config.

**Comment by lurr** [comment]
Appears to be working again after SpongePowered/SpongeCommon@9b220c0c983adcd2c1d6ed92687d93417e10f391

**Comment by Tangosucka** [comment]
Still an issue

**Comment by Eufranio** [comment]
It seems to be fixed in the last Sponge version.
