### ISSUE TITLE
Feature request: support for other bridges

### ISSUE THREAD

**Issue by Lgmrszd** [Eufranio/MagiBridge#142]
For example, I have IRC <-> Discord bridge and MagiBridge running. If someone sends message in IRC, it will appear in MC chat like `[discord]irc-bridge: irc-user: message`, which looks kinda weird. Or if I'm using MatterBridge, it becomes `[discord]bridge: [IRC] irc-user: message`. I suggest implementing a feature which allows to parse message from other bots (maybe add option to config to allow custom Regex) and print them in chat in more neat manner.
Another problem: If some other bot use Webhook api to relay messages, they aren't detected by MagiBridge, so it would be nice if they would be detected and parsed too.

**Comment by Asherslab** [comment]
So, i saw this when it was first posted, and i just thought since there's been no response that i'd say something.
A) I think that sort of feature would kind of be outside of the scope of this more "simple" plugin, of course i could be completely wrong! that's obviously a thing that's up to Eufranio
B) I'm working on a project that would be for more advanced setups like what you want, e.g. link discord <-> slack <-> mc server <-> IRC together. Of course it's still in heavy WIP. However i just thought i'd share what i had to say

**Comment by Lgmrszd** [comment]
> B) I'm working on a project that would be for more advanced setups like what you want, e.g. link discord <-> slack <-> mc server <-> IRC together. Of course it's still in heavy WIP. However i just thought i'd share what i had to say

I'll suggest you to look at [matterbridge](https://github.com/42wim/matterbridge), an ultimate relay (which has simple api for other services) and at [MatterLink](https://github.com/elytra/MatterLink), forge mod which uses MatterBridge to relay messages between mc server and other services. However, MatterLink is a mod, not a plugin, so it doesn't support Nucleus or other plugins. It is also cause server lag in some cases and made server crash a few times. I've contacted MatterLink developer and he said that this mod needs to be either reworked or rewrited. If you're developing plugin for Sponge, I'll suggest you to check this mod and Matterbridge itself.

**Comment by Asherslab** [comment]
@Lgmrszd yeah, i'm developing my own services and api for it, not using an external one =D

**Comment by Asherslab** [comment]
Now that i'm thinking about it, out of curiosity, what features specifically are you looking for in regards to Nucleus support? I may be able to provide similar features without the need for it being a plugin

**Comment by Lgmrszd** [comment]
> 
> 
> Now that i'm thinking about it, out of curiosity, what features specifically are you looking for in regards to Nucleus support? I may be able to provide similar features without the need for it being a plugin

MagiBridge supports separate general and staff chats (last one provided by Nucleus). But that's not the feature I'm looking for, it's just a feature MagiBridge can do.

**Comment by Asherslab** [comment]
what features are you looking for? because currently mine is able to support any number of channels.

**Comment by Lgmrszd** [comment]
I think it's better to continue discussion somewhere else since it is not related to MagiBridge and my feature request.

**Comment by Eufranio** [comment]
You can do this with code (yourself or adding as a hook to MagiBridge). Just request compatibility with whatever that IRC plugin is and I can see what I can do.
