### ISSUE TITLE
Feature Request: MultiChat (Bungee) plugin support

### ISSUE THREAD

**Issue by JDHallows** [Eufranio/MagiBridge#143]
MultiChat is chat system that allows cross-server chat over Bungee. Would it be possible to add support for MultiChat? Sponge Ore page: https://ore.spongepowered.org/Revilo/MultiChat

MultiChat does have a listeners API per https://github.com/MultiChat/Development/wiki/Chat-Events

**Comment by Eufranio** [comment]
I can try, but I don't have a MultiChat setup so I can't do much testing.

**Comment by Eufranio** [comment]
Actually, there's no way that a Sponge plugin could intercept the MultiChat messages on its own, so this is not gonna happen until the MultiChat adds a way to do so, sorry.

For reference: https://github.com/MultiChat/Development/issues/67
