### ISSUE TITLE
Magibridge connection issues with minecraft chat

### ISSUE THREAD

**Issue by Wrizzler** [Eufranio/MagiBridge#144]
For my server, the plugin appears to send join, leave, start, and stop messages as well as let discord users send messages to the minecraft server, but no minecraft chat is sent back. I saw a similar issue where removing the %prefix% variable fixed it, unfortunately this did not resolve my issues. Please let me know of any other ideas to try. I am running Nucleus on feed the beast ultimate reloaded.

**Comment by ktole1999** [comment]
its a config issue. make sure chat IDs are correct. look here:

# ID of the main Discord Channel, where start/stop messages will be sent to
    main-discord-channel=""
    # IGNORE IF USING ULTIMATECHAT!
    nucleus {
        # Discord Channel ID which global messages are sent to
        global-discord-channel=""
        # Channel that HelpOp messages will be sent to (if enabled)
        helpop-channel=""
        # Discord Channel ID which messages from the staff chat are sent to
        staff-discord-channel=""


Also make sure your bot is setup correctly. Once i setup this everything worked for me.

**Comment by Eufranio** [comment]
This is probably due to bad configuration, take a look on your current config values. If you still have problems come on our Discord and send your config.
