### ISSUE TITLE
Bot Blocking

### ISSUE THREAD

**Issue by stw222** [Eufranio/MagiBridge#145]
Something that i have liked about DiscordSRV for spigot servers is that it doesnt transmit text in a discord channel that is from other bots. Could you make this a feature for this plugin? I am a head admin for a bungeecord network and we have a bot for each server to be able to transmit discord <-> mc messages for each and the ignore bot messages really helps. it also doesnt help when something like Mee6 chimes in.

**Comment by ktole1999** [comment]
cant you achieve the same result by denying unauthorized bot write access in that specified channel?

**Comment by stw222** [comment]
No, we have a bot for the chat of each server in a single channel. Our 3 spigot servers are fine with that because discordsrv has a deny bot option. Dsrv is not on sponge so we had to look for a different solution. We want people to be able to send a message in 1 channel and be able to talk to anyone. Our chat in game is already connected to all servers so it would be weird if only 1 server could see a chat message.

Currently with this plugin, it duplicates chat from other servers.

You get the chat normally from whatever server, but then get the bot message from discord which has different formating so its all a big mess

**Comment by ktole1999** [comment]
Ahhh i misunderstood what you were asking. Makes sense. Yes that would be a good feature.



Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone


-------- Original message --------
