### ISSUE TITLE
Exception's with messages containing "@ "

### ISSUE THREAD

**Issue by ChatonIsHere** [Eufranio/MagiBridge#150]
The following exception is thrown when a message is sent with an "@" symbol followed by whitespace or the end of the message:

```JAVA
java.lang.IllegalArgumentException: Name may not be empty
```

Full error here: https://mclo.gs/C4GUr02

It means the players can say things in-game without it appearing in Discord, and all they have to do is include "@ " somewhere in the message or just end the message with the "@" character.

**Comment by Eufranio** [comment]
Please try with the new version.
