### ISSUE TITLE
[GitHub Release 2.8] Link to Sponge broken, For people who may come for that

### ISSUE THREAD

**Issue by ROMVoid95** [Eufranio/MagiBridge#152]
This isn't a issue with the bot, but i've had a few people from my server network complain that one of the first links from google for the plugin leads them to 
-> [Sponge](https://forums.spongepowered.org/t/magibridge-a-utility-discord-minecraft-chat-relay-plugin/19796), which has a download link to 
-> [ReleaseTab](https://github.com/Eufranio/MagiBridge/releases), where the [latest Release ](https://github.com/Eufranio/MagiBridge/tree/v2.8) links back to 
-> [Sponge Ore Version 2.8](https://ore.spongepowered.org/Eufranio/MagiBridge/versions/2.8) that doesn't exist anymore.

For anyone here for that, url just needs /2.8 removed.
https://ore.spongepowered.org/Eufranio/MagiBridge/versions

**Comment by Eufranio** [comment]
Sorry for that. People are supposed to download it from Ore, but the link from the post (`This is a discussion topic for the Ore project, MagiBridge`) is broken so I had to add the link to the post description, and releases isn't being used anymore. It's fixed now.
