### ISSUE TITLE
Don't showing achievements on my Discord channel

### ISSUE THREAD

**Issue by corrompu-github** [Eufranio/MagiBridge#154]
Hi! Since yesterday I try to show up achievement of player on my Discord channel. 
I'm thinking that the mistake must probably come from me because english isn't really my first language but anyway you have the link of my MagiBridge.conf

https://pastebin.com/yGzcCEpQ

I also have 220 Mods maybe one of them change how vanilla achievement work? I didn't know

**Comment by Eufranio** [comment]
Please try with the new version.

**Comment by 2iguys** [comment]
I am having a similar issue, it won't show the advancements in discord, but also it has shown just this (see below) with no detail of which advancement.

2iguys got a new advancement: Minecraft
2iguys got a new advancement: Minecraft

For reference I am running a Tekxit 3 server for this specific issue, it happens as well on a Stoneblock 2 server too.
