### ISSUE TITLE
§ character not being replaced

### ISSUE THREAD

**Issue by ROMVoid95** [Eufranio/MagiBridge#157]
i applaud you sir for this feature it has been one i have been waiting for. Afaik all is well and works as it should except for the § character doesn't seem to be replaced as it should be after looking at the class file. 
https://imgur.com/a/4C3QIhD

forge-1.12.2-14.23.5.2847
spongeforge-1.12.2-2838-7.1.7-RC3928
MagiBridge-API7-2.9

**Comment by Eufranio** [comment]
Should be fixed in the last versions.
