### ISSUE TITLE
REQUEST - Implement Discord-based whitelisting/link player and discord accounts

### ISSUE THREAD

**Issue by vico93** [Eufranio/MagiBridge#161]
After playing on DigitalJesuit, i thought if is possible to recreate the system they use for authentication: first players need to join the server (and stay frozen in place/or in a lobby), do `/discord link` and then a special code is given.

Then they need to send via inbox this code for the BOT, it verify if the player is in the discord server and if positive it "link" both discord and minecraft accounts, allowing the player to join the server.

I think if the player is banned/kicked of discord server they cant join the minecraft server as well, basically acting like a whitelist.

Is possible to something similar to be implemented in this plugin?

**Comment by Asherslab** [comment]
https://github.com/Eufranio/MBDiscordLink

**Comment by vico93** [comment]
Thanks for the tip
