### ISSUE TITLE
Console Discord Channel Issue

### ISSUE THREAD

**Issue by Xeliphix** [Eufranio/MagiBridge#162]
I just add MagiBridge to my server, and it's a very cool thing !
But, I have a problem with the Console Discord Channel, it spam the discord channel I choosed of errors :
[DiscordChat-send-queue/ERROR] [discordchat] Error sending message to Discord: 10003 (Unknown Channel)
[DiscordChat-send-queue/ERROR] [discordchat] Error sending message to Discord: 10003 (Unknown Channel)
[DiscordChat-send-queue/ERROR] [discordchat] Error sending message to Discord: 10003 (Unknown Channel)
[DiscordChat-send-queue/ERROR] [discordchat] Error sending message to Discord: 10003 (Unknown Channel)
[DiscordChat-send-queue/ERROR] [discordchat] Error sending message to Discord: 10003 (Unknown Channel)

**Comment by Asherslab** [comment]
Looks to me like in your config you set the channel ID as 10003, am i correct? if so then that's an invalid channel ID

**Comment by Eufranio** [comment]
You're using DiscordChat (by what the log looks like), not MagiBridge.
