### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by confuser** [Eufranio/MagiBridge#164]
Looking at integrating this with BanManager to send ban notifications to Discord for Sponge. Already have this implemented in Bukkit via DiscordSRV. I can't see an API documented for this at the moment, just listening on messages already sent.

Is this the recommended way? https://github.com/Eufranio/MagiBridge/blob/api-7/src/main/java/com/magitechserver/magibridge/listeners/UChatListeners.java#L34-L44 using `DiscordMessageBuilder`?

**Comment by Eufranio** [comment]
I will get to document everything sometime soon, but for now, [MBDiscordLink](https://github.com/Eufranio/MBDiscordLink) is a good example of how the MagiBridge API can be used.

* You can listen **directly** to Discord messages by registering a `ListenerAdapter` to JDA, via [JDA#addEventListener](https://github.com/Eufranio/MBDiscordLink/blob/api-7/src/main/java/com/magitechserver/mbdiscordlink/MBDiscordLink.java#L139)
* You can send messages to Discord via the [DiscordMessageBuilder](https://github.com/Eufranio/MagiBridge/blob/api-7/src/main/java/com/magitechserver/magibridge/discord/DiscordMessageBuilder.java)
* You can send messages to the server via the [ServerMessageBuilder](https://github.com/Eufranio/MagiBridge/blob/api-7/src/main/java/com/magitechserver/magibridge/chat/ServerMessageBuilder.java)

MagiBridge also has a [DiscordMessageEvent](https://github.com/Eufranio/MagiBridge/blob/api-7/src/main/java/com/magitechserver/magibridge/events/DiscordMessageEvent.java), which is a simpler and most recommended way of listening to the messages. You can get the `MessageBuilder` used in the event, cast it to the implementation one (ServerMessageBuilder/DiscordMessageBuilder) and modify it as you want, or simply cancel the event.

If you have any more questions, feel free to join the plugin's Discord server or just add them here.

**Comment by confuser** [comment]
Thanks for the quick response! Was able to integrate after a bit of digging around 👍
