### ISSUE TITLE
Multichat support?

### ISSUE THREAD

**Issue by Spontini** [Eufranio/MagiBridge#168]
Can you add MultiChat support, please?

https://www.spigotmc.org/resources/multichat.26204/
https://ore.spongepowered.org/Revilo/MultiChat

**Comment by Eufranio** [comment]
According to [this](https://github.com/MultiChat/Development/issues/67#issuecomment-615286148), MultiChat should work with MagiBridge if you have MB set to listen to the vanilla chat.
