### ISSUE TITLE
!online Typo and Formatting Issues

### ISSUE THREAD

**Issue by Sade66** [Eufranio/MagiBridge#17]
1. There is a typo in the online player list;
![image](https://user-images.githubusercontent.com/19366945/28345874-fe5b2d10-6bfa-11e7-84fd-c0cefd887312.png)

2. Players' prefixes and names come through the `%message%` modifier of `server-to-discord-format` along with the users' message.

3. The `prefix` modifier of `server-to-discord-format` shows the Minecraft chat formatting (color) codes.

![image](https://user-images.githubusercontent.com/19366945/28345930-7134dd0e-6bfb-11e7-9467-1dab60c9bf94.png)

**Comment by Eufranio** [comment]
Hey @Sade66, could you test with the latest build from [here](https://github.com/Eufranio/MagiBridge/releases/tag/pre-1.8%2C1)?

**Comment by Sade66** [comment]
I sure can, thanks! :)

_Sent from my Motorola XT1585 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
