### ISSUE TITLE
Chat and commands not working in either direction.

### ISSUE THREAD

**Issue by ghost** [Eufranio/MagiBridge#173]
From within Minecraft, chat messages and /helpop are working, but not appearing in Discord.
From within Discord, !cmd and !online are not working either.

My config is [here](https://pastebin.com/fwJfTetf), and I am supposing that there is something wrong with it, but I can't seem to figure it out.

I am using LuckPerms v5.0.78, Nucleus v1.14.2, MagiBridge v2.9.2. I have notifications coming in to Discord from Minecraft, but no commands or chats. LuckPerms/Nucleus checks out from what I can tell, as I can chat openly, and can use the /helpop command. MagiBridge also has both "Manage Channels" and "Manage Webhooks" permissions in Discord.

Please advise; thank you!

**Comment by Eufranio** [comment]
Check your console for errors, maybe the bot is missing some permission, and try with webhooks disabled (if it works, the bot probably doesn't have permission to send webhooks to specific channels).
