### ISSUE TITLE
[net.dv8tion.jda.internal.requests.RateLimiter]

### ISSUE THREAD

**Issue by XCharmyX** [Eufranio/MagiBridge#176]
Hi im getting some ratelimiter warnings that floods my console, do you have any clue as to how it can be fixed?
Errors looks like this
29.05 12:07:29 [Server] JDA RateLimit-Worker 4/WARN [net.dv8tion.jda.internal.requests.RateLimiter]: Encountered 429 on route /channels/(CHANNEL ID)

**Comment by Asherslab** [comment]
That would mean that your server is sending too many messages to discord at once (spam) this is discord's API blocking you

**Comment by XCharmyX** [comment]
Is there anyway i can prevent the api blocking me? Im not too tech savy or have that large reservoir of knowledge when it comes to discord

**Comment by Asherslab** [comment]
> your server is sending too many messages

you need to decrease the messages your server is sending. do you have multiple servers on one bot or machine?

**Comment by XCharmyX** [comment]
I have one bot on one server

**Comment by Asherslab** [comment]
Okay, well then you need to reduce the amount of messages you're sending to discord, possibly try and disable the channel description updating feature

**Comment by XCharmyX** [comment]
doesnt seem to do anything

**Comment by T3DDY14** [comment]
I've got the same issue but I've got 2 different bots on 2 different plugins on the same machine, as i use magibridge for modded and discordsrv for vanilla, never used to have this

**Comment by XCharmyX** [comment]
Mine just started over night seemingly from out of nowhere, I've used magibridge for a short while now, but it just happend all of a sudden

**Comment by T3DDY14** [comment]
ive been using it for a few months and never had this even with multiple servers on the same server with different bots

**Comment by Eufranio** [comment]
Looks like MagiBridge is getting rate limited because of the topic updater. For now, disable it on your config and the error should stop. I'll research about it when I get to my computer again, and while that I'll leave this open so I can update you.

**Comment by PsalmsFighter** [comment]
I'm also having this issue, I'll do the suggested temp fix but I'd love to hear if anyone has another solution since the topic updater is a really cool feature that I'd like to keep!

**Comment by T3DDY14** [comment]
this isnt a fix but ive found its not just magibridge, discordsrv is also having this issue, so i think it might be a discord side

**Comment by Eufranio** [comment]
I increased the min topic updater time to 10 minutes on the latest version, this should fix the errors.

**Comment by NopeDK** [comment]
I would recommend switching from a delay to use Discords recommended practices of reading the rate limit response and adjust the delay until next topic update accordingly.
