### ISSUE TITLE
JDA RateLimit-Worker 2/WARN

### ISSUE THREAD

**Issue by padakoys** [Eufranio/MagiBridge#177]
I am getting these warnings the last 2 days without changing anything from my config files.

[18:24:52] [JDA RateLimit-Worker 2/WARN] [net.dv8tion.jda.internal.requests.RateLimiter]: Encountered 429 on route /channels/684884215023****** 

I am using it for only one channel.

**Comment by Eufranio** [comment]
Please update to 2.10.3+, this was already fixed.

**Comment by padakoys** [comment]
I will inform you after my scheduled server restart. Thank you for your time.

**Comment by padakoys** [comment]
No warnings so far, thank you.
