### ISSUE TITLE
Using code blocks for console to discord does not work sometimes

### ISSUE THREAD

**Issue by ghost** [Eufranio/MagiBridge#178]
![Screenshot 2020-06-02 at 14 45 06](https://user-images.githubusercontent.com/22250416/83488730-e97a7380-a4df-11ea-8aea-f635b3eb4251.png)

I added a ` to the front and back of all text. It works most of the time, except when the text is really long like this.

**Comment by Eufranio** [comment]
Not sure what I can do about this, it's happening because the text is being split into two messages. Maybe add a filter that cuts long messages? I'll keep this open for now.

**Comment by Eufranio** [comment]
Since there's been no new information, I'm closing this.
