### ISSUE TITLE
Send mc uuid/name to chat for whitelisting

### ISSUE THREAD

**Issue by Zaragan** [Eufranio/MagiBridge#179]
Hi! It's possible to send some message to a discord designated chat for whitelisting a player and remove from whitelist when they're removed from the discord server?

#whitelist
Name: MinecraftName Uuid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

When the prefformated text is detected bot adds the MinecraftName to the whitelist. We might need to vinculate the discord username (@something#0000) to the minecraft username to be able to remove them from the whitelist when a user leaves a certain role.

Thank you!

**Comment by Pulz-TCP** [comment]
This sounds beyond the scope of MagiBridge, or perhaps an enhancement for [MBDiscordLink](https://github.com/Eufranio/MBDiscordLink)

**Comment by Eufranio** [comment]
Yeah, out of the scope of MagiBridge, which focuses on chat sync. Maybe for an addon.
