### ISSUE TITLE
Feature Idea: Hover over name in Minecraft for Discord invite

### ISSUE THREAD

**Issue by Sade66** [Eufranio/MagiBridge#18]
Kind of like how you can hove over a player's name in Minecraft to message them, it would be cool if hovering over a Discord user's name in chat would give the player in invite to the server.

![image](https://user-images.githubusercontent.com/19366945/28386676-4cb5a8f6-6c9a-11e7-8744-7074c33efcbb.png)

So when you hover over someone's name from Discord, it would show something like *Message from Discord* on the first line, then *Join our Discord by clicking*. Hopefully the messages and Discord link would all be configureable via the config.

**Comment by Eufranio** [comment]
Won't be doing this now, in the future I will replace the whole String system to Text system (so I can add hover, click and suggest messages), and will implement it along with #5.

**Comment by Eufranio** [comment]
@Sade66 could you test [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-2.0.2-all.jar)? I've added some new fields to the config, where you can set the prefix of Discord messages coming to MC, as well as it's hover and clickable texts.

**Comment by Sade66** [comment]
@Eufranio I will test this, thank you! :)
