### ISSUE TITLE
[Error] java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by poqdavid** [Eufranio/MagiBridge#182]
Today when I attempted to run a command (/sponge timings paste) on the bridge server crashed instantly and jere is the error https://hastebin.com/ijowukomoh

Forge: 14.23.5.2847
SpongeForge: 1.12.2-2838-7.2.1
Nucleus: 1.14.5-S7.1
MagiBridge: 2.10.2

**Comment by Eufranio** [comment]
Update MagiBridge.
