### ISSUE TITLE
Bridge re-sents server messages back to server when "ignore-bots=false" 

### ISSUE THREAD

**Issue by Lgmrszd** [Eufranio/MagiBridge#189]
Latest version featured option to not ignore other bot's messages. While it is indeed working with other bots, it also makes it so plugin catches messages it sent itself. If someone sends message in-game, it will also appear as sent from discord.

This happened on FTB Interactions pack (Forge version 14.23.5.2847), with SpongeForge version 1.12.2-2838-7.3.0 and MagiBridge version 2.11-nucleus-2.0.4. The only other plugins installed were Boop and spark. I haven't tested it with only MagiBridge, although I'm sure this problem will occur.

**Comment by Electrofried** [comment]
Can confirm the bot is echoing its own messages, the ability to link multiple discord bots in one channel is very handy but with the echo the function is unusable.

**Comment by jev217** [comment]
This issue is existing for me as well.

**Comment by Eufranio** [comment]
Should be fixed on 2.12.
