### ISSUE TITLE
Request: add player’s prefix for the list of online players

### ISSUE THREAD

**Issue by fcpwiz** [Eufranio/MagiBridge#19]
I’d love to see the player’s rank/prefix in front of each of their usernames when the !online command is activated.

**Comment by Eufranio** [comment]
Hey @fcpwiz, could you test with latest build from ![here](https://github.com/Eufranio/MagiBridge/releases/tag/pre-1.8%2C1)?

**Comment by fcpwiz** [comment]
Yep, will do! Thanks!

**Comment by fcpwiz** [comment]
Hi @Eufranio, here's what the !online list looks like now:
<img width="803" alt="screen shot 2017-07-20 at 8 08 41 am" src="https://user-images.githubusercontent.com/2921172/28416609-b690e910-6d22-11e7-8ba6-c169978ed468.png">

**Comment by Sade66** [comment]
@fcpwiz We can adjust some of that from the config. The prefix color codes are a different issue which I already reported.

_Sent from my Motorola XT1585 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fcpwiz** [comment]
@Sade66 Right, but I'm also reporting the 2 commas after my username.

**Comment by Sade66** [comment]
I know, I added a comma in the configs, I can remove it.

_Sent from my Motorola XT1585 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Eufranio** [comment]
Hey @fcpwiz, could you test using [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.8.1-all.jar) now?

**Comment by fcpwiz** [comment]
@Eufranio Ok, now I'm getting this: 
<img width="822" alt="_server-chat_-_discord" src="https://user-images.githubusercontent.com/2921172/28444084-781a5700-6d88-11e7-92c9-ff3806b552f2.png">

The config line: `player-list-name="%prefix% %player%"`

**Comment by Eufranio** [comment]
Fixed it with https://github.com/Eufranio/MagiBridge/commit/1361e5ad6a226c6092ae45d8b6575bfae299cc30, could you test with [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.8.1-all.jar)?

**Comment by Eufranio** [comment]
Assuming it's fixed.
