### ISSUE TITLE
Disable discord bot logging 

### ISSUE THREAD

**Issue by ghost** [Eufranio/MagiBridge#190]
As the title says, I want to be able to disable discord bot logging

![image](https://user-images.githubusercontent.com/24543050/93018924-1e7d8280-f606-11ea-9a46-8e84ce688b0c.png)

**Comment by Eufranio** [comment]
The default log level for JDA should be INFO for console and DEBUG for the log file, but for some reason you have it set to TRACE. If you want to, you can change the log level for JDA via a log configuration file: https://docs.spongepowered.org/stable/it/server/spongineer/logs.html#configure-logging

I suggest leaving it at least on INFO: `<Logger name="magibridge.net.dv8tion.jda" level="info"/>`
