### ISSUE TITLE
Latest version not working in 1.10.2...

### ISSUE THREAD

**Issue by GraphicHealer** [Eufranio/MagiBridge#192]
So I tried to install the latest version in minecraft 1.10.2, and it somewhat works, like the commands and chat from discord show up in minecraft, but the minecraft chat does not go to discord. What do I do?

**Comment by Eufranio** [comment]
Not sure if I want to support versions too old like 1.10.2, but I'll keep this open.

**Comment by GraphicHealer** [comment]
1.10.2 was not the Minecraft version. It was the version of your plugin.

**Comment by GraphicHealer** [comment]
Oops. Forgot which GitHub thing this was.

**Comment by Eufranio** [comment]
Is there any issue with MagiBridge? If so, please test with the new version, 2.12. If it doesn't work, provide logs so I can take a look.

**Comment by GraphicHealer** [comment]
I misspoke. I forgot which GitHub thing this is. I was thinking of a plug-in for a velocity not for sponge. I honestly don't remember last I used this plugin.

**Comment by Eufranio** [comment]
Okay.
