### ISSUE TITLE
[SUGGESTION]

### ISSUE THREAD

**Issue by TetraFlash** [Eufranio/MagiBridge#194]
Support for Sponge Broadcasts (so I am told they are called).  Specific example would be messages broadcasted from "Pixelmon Broadcast" https://pixelmonmod.com/wiki/Pixelmon_Broadcasts.  

This would allow in-game events to inform the discord users it is happening.  Hopefully resulting in a bunch of people hoping on to take part.

**Comment by Eufranio** [comment]
I can add support for relaying the minecraft's/nucleus' `broadcast` command, but relaying those pixelmon broadcasts are out of the scope of MagiBridge. If you still want it, ask the sidemod developers for adding some support for MagiBridge, the API is very easy to use, and I'm available for any questions.
