### ISSUE TITLE
%message% being sent in helpop but no other channels

### ISSUE THREAD

**Issue by d-kreitzer** [Eufranio/MagiBridge#199]
Nucleus version: 1.14.3
Magibridge version: 2.11.1

I'm not getting any error messages, but when /helpop is used in game Discord is reflecting: "Raully61: %message%". My channels are all correct in the config and the bot is correctly updated as well, since general and staff chat is still working fine.

**Comment by Eufranio** [comment]
Should be fixed on 2.12.
