### ISSUE TITLE
BungeeChat support

### ISSUE THREAD

**Issue by EmanYm** [Eufranio/MagiBridge#2]
Here's the [BC github](https://github.com/AuraDevelopmentTeam/BungeeChat2) and the [Spigot page](https://www.spigotmc.org/resources/bungee-chat.12592/).  Also the [Discord channel](https://discord.me/bungeechat) in case you need that

**Comment by Eufranio** [comment]
Asked the BungeeChat dev on Discord about this suggestion, and there is no effective way of MagiBridge handle the chat through Sponge, and I'm not gonna make a BungeeCord plugin just for this **yet**. Sorry.

**Comment by EmanYm** [comment]
No problem.  It was mostly an "ease-of-life" request anyway.
