### ISSUE TITLE
Configuration file auto-migration

### ISSUE THREAD

**Issue by Sade66** [Eufranio/MagiBridge#20]
Currently, when updating the plugin, I have to copy the old config and then delete it, so a new config will be made with the new options. What would be really helpful, and [DIscordSRV](https://github.com/scarsz/DiscordSRV/) does this, is if when you get and updated version of the plugin, it would move all your old settings over to the new config, and just leave the new options default. Then mark the old config as `config_version[version].conf` or something like that. This would make updating a lot easier.

**Comment by Eufranio** [comment]
The config should now be automatically migrating with the new config system.
