### ISSUE TITLE
Plugin not detected 

### ISSUE THREAD

**Issue by Matemarthur** [Eufranio/MagiBridge#200]
A few weeks ago Magibridge stopped working. 
I tried to run the commands but instead of send a message to my discord server I got the message "Unknown command, try /help" 
Also tried older versions but got nothing. 

We really love this plugin.

**Comment by Eufranio** [comment]
Which version are you using? A few weeks ago I did release an update to fix those issues.

**Comment by Matemarthur** [comment]
Thnaks for answering, I'm using this version MagiBridge-API7-2.10.0.

I saw the last relase but it was a zip and since it was not a jar file I didn't downloaded it.

**Comment by Eufranio** [comment]
MagiBridge should be downloaded from Ore.
