### ISSUE TITLE
Error loading Magibridge

### ISSUE THREAD

**Issue by Matemarthur** [Eufranio/MagiBridge#201]
Hi there again and thans for responding last time. 
Now I have a new error and I don't know how to fix it :( 

17.11 20:09:18 [Server] pool-3-thread-12/ERROR [magibridge]: Error loading MagiBridge:
17.11 20:09:18 [Server] INFO java.lang.NoClassDefFoundError: io/github/nucleuspowered/nucleus/api/module/afk/event/NucleusAFKEvent

Magibridge now sends the message when server stops and I can execute commands from my DC channel but nothing else.

**Comment by Matemarthur** [comment]
Solved ! 
It was an issue with my Nucleus version.

**Comment by quinn-brittain** [comment]
@Matemarthur What were your steps to fix this. I have the same issue.

**Comment by Matemarthur** [comment]
Just updated Nucleus and Sponge to their latest versions.
