### ISSUE TITLE
[Suggestion] Allow Discord channel ID to be used in /mb or /mbroadcast instead of channel name

### ISSUE THREAD

**Issue by Mike5357** [Eufranio/MagiBridge#205]
Currently, /mb or /mbroadcast cannot be used if an emoji is present within a Discord channels name (ie. "💬general-chat").
Since emojis cant exactly be entered into Minecrafts chat to enter the command for such channels, allowing a Discord channels ID to be used as well would allow better compatibility for specific use-cases such as ours.

**Comment by Caaethil** [comment]
I would also like to see a way around this. Emojis in channel names look nice and can help with navigation at a glance, especially in servers with a lot of channels. And having one or two channels without an emoji in the name can look pretty odd.
