### ISSUE TITLE
Posting a message in-game containing a single "@" symbol throws an error and the message is not posted in the main Discord channel

### ISSUE THREAD

**Issue by Caaethil** [Eufranio/MagiBridge#211]
Console error: https://pastebin.com/XbyxcsTQ

Only happens with lone @ symbols, so "@ hello" or "hello @ world" would throw this error and not be posted, but "@@@" would be posted. Messages are always posted in the console, this issue is solely with main chat. The issue appears to be that MagiBridge is trying to convert text following the @ symbol into a Discord mention. This could cause problems if someone types something like "I'm @ my base" as shorthand, or if someone just wants to use the symbol so someone on Discord doesn't see the message.

**Comment by Eufranio** [comment]
Should be fixed on 2.12.
