### ISSUE TITLE
Role mentions not working in main channel

### ISSUE THREAD

**Issue by Caaethil** [Eufranio/MagiBridge#212]
When I mention a role in-game, the role is correctly pinged in my console channel, but in the main channel it appears as `<@insertnumbershere>`.

Pinging individual users or @everyone works just fine.

**Comment by Eufranio** [comment]
Apparently webhooks are not able to mention roles, and I have no idea why. Since this is not a MagiBridge limitation, I'm closing this. If you have some info on how I could fix that on the MagiBridge side, please let me know.

**Comment by Eufranio** [comment]
It seems to be fixed on 2.12.
