### ISSUE TITLE
[Suggestion] MC-to-Discord Replacer (to go with the Discord-to-MC Replacer)

### ISSUE THREAD

**Issue by Caaethil** [Eufranio/MagiBridge#214]
This would let people type something like ":)" in-game and have it convert to the correct emoji on Discord (like how the opposite can be done with the existing Discord-to-MC replacer).

My (more niche) reason for wanting to this is because I use the mcmoji plugin (which puts emojis in-game by converting codes like `:this:` into Chinese characters (and then uses a resource pack to make those characters look like emojis), and I would like to be able to convert from those Chinese characters to the emojis they represent when posting from in-game to Discord. This is a more niche use though.

Overall this suggestion probably shouldn't be a priority but I thought I'd drop it in anyway. :)

**Comment by Eufranio** [comment]
Will add that.

**Comment by Eufranio** [comment]
Should be included in 2.12.
