### ISSUE TITLE
Nucleus Helpop leaks

### ISSUE THREAD

**Issue by ItsaGlitch1** [Eufranio/MagiBridge#217]
When someone uses helpop, in the specified helpop channel, the message is %message%. It doesn't grab the message and when you talk into the specified helpop channel, from discord, it gets shown to public chat. Also helpop messages get put into the regular chat with the actual message.

![1](https://user-images.githubusercontent.com/23035675/112706034-fa81e000-8e77-11eb-888f-1a8a22e6874f.PNG)
![2](https://user-images.githubusercontent.com/23035675/112706036-fb1a7680-8e77-11eb-937f-b4a67aed07b0.PNG)
![3](https://user-images.githubusercontent.com/23035675/112706035-fa81e000-8e77-11eb-884d-9a2ad9d19504.PNG)

**Comment by Eufranio** [comment]
Should be fixed on 2.12.
