### ISSUE TITLE
Capitalize first letter of %toprole%

### ISSUE THREAD

**Issue by fcpwiz** [Eufranio/MagiBridge#22]
With LuckPerms, a rank cannot begin with a capital letter. It would be great if %toprole% would automatically make the first letter of the role capitalized (`[owner]` to `[Owner]`).

**Comment by Eufranio** [comment]
It's up to the permission plugin, you can do it yourself with the groups' display name, feature from LuckPerms. 

Reopen if you have any other issues using it.
