### ISSUE TITLE
[Suggestion] More broadcast relay options

### ISSUE THREAD

**Issue by OzTheM9** [Eufranio/MagiBridge#229]
![image](https://user-images.githubusercontent.com/73391963/122975759-fc364380-d393-11eb-8c72-3f5b7550b78f.png)

Magibrige currently supports Nucleus broadcasts, but that leaves out other potential restarts like the one in the provided picture. Would it be possible to add support for other plugins/mods?

**Comment by Eufranio** [comment]
That depends of the other plugin, it would probably need a specific integration in MagiBridge for each plugin/message/event to be relayed. You can suggest a specific integration though, and I can take a look if it's viable to implement.
