### ISSUE TITLE
!online Suddenly not Working

### ISSUE THREAD

**Issue by Sade66** [Eufranio/MagiBridge#23]
I have my online list command for Discord set to `.players`. Everything was working fine but suddenly (even after multiple restarts), the list just doesn't show. `.cmd` still works but for some reason the player list isn't.

My config is set to the following for the list:
```
# Discord command that shows the current online player list
player-list-command=".players"
```

```
# Format of the player name displayed in the channel list command (!online)
# Supports %player% and %prefix%
player-list-name="%prefix% %player%"
```

**Comment by Eufranio** [comment]
Are you isso issuing the command in a listenable channel (main, staff, global...)?
Have you tried changing the command to another one? 
Could you send your fml-server-latest.log?

**Comment by Sade66** [comment]
1. Yes.
2. No.
3. Sure, I'll DM it to you on Discord.

**Comment by Eufranio** [comment]
What happens if you use another (or the default) player list command name? like `!online` or so.

**Comment by Eufranio** [comment]
Assuming it's fixed.
