### ISSUE TITLE
Users cant read discord messages. Nucleus Issue

### ISSUE THREAD

**Issue by NomcciDubs** [Eufranio/MagiBridge#238]
Hello, in my server with LuckyPerms the users cant read messages from discord to minecraft but the mods with nucleus.mod permission can read the messages. The bot have all the permissions of discord and member intent, but i dont know what is the permission of nucleus that is creating the issue.
Thanks in advance

**Comment by Eufranio** [comment]
This looks like a permissions issue, you can try to look which permissions you're missing by using the LuckPerms verbose command. In the MagiBridge side, users only are required to have the `magibridge.chat` permission.
