### ISSUE TITLE
Add %prefix% support for join and leave messages

### ISSUE THREAD

**Issue by fcpwiz** [Eufranio/MagiBridge#24]

**Comment by Eufranio** [comment]
@fcpwiz, please test with [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.8.1-all.jar) and let me know if it works.

**Comment by Eufranio** [comment]
Assuming it's fixed.

**Comment by fcpwiz** [comment]
<img width="369" alt="_server-chat_-_discord" src="https://user-images.githubusercontent.com/2921172/28879452-7deb5386-77a2-11e7-8946-1584f9a4b0cd.png">
<img width="326" alt="_server-chat_-_discord" src="https://user-images.githubusercontent.com/2921172/28879520-a650aa4c-77a2-11e7-8788-7d979d2f89d6.png">

Using MB 1.9.1, prefixes still don't show on join and leave messages.

**Comment by Eufranio** [comment]
Do you have the %prefix% in the config message?

**Comment by fcpwiz** [comment]
Oh jeez, no I didn’t. Does it also support %toprank%?
