### ISSUE TITLE
Ignore CustomNPCs messages

### ISSUE THREAD

**Issue by PixelmonPRO** [Eufranio/MagiBridge#25]
Hello! Many NPCs from the CustomNPC mode have their own dialogs.
![2017-07-22_04 17 01](https://user-images.githubusercontent.com/26658563/28487225-401c2dde-6e95-11e7-8519-71979c9ff8a6.png)
![2017-07-22_04 16 56](https://user-images.githubusercontent.com/26658563/28487228-439be8be-6e95-11e7-88c9-bdce290bc39e.png)
![2017-07-22_04 19 46](https://user-images.githubusercontent.com/26658563/28487230-461bc0d2-6e95-11e7-9367-2d99e4d89303.png)
And all these messages are broadcast to Discord:
<img width="420" alt="screenshot at 22 04-20-03" src="https://user-images.githubusercontent.com/26658563/28487236-5ee27b42-6e95-11e7-8557-7c4f48ef2d83.png">
NPC create for texture Pokemon broadcast messages too:
![2017-07-22_04 24 12](https://user-images.githubusercontent.com/26658563/28487325-b591465c-6e96-11e7-9f00-ddcaaee7f409.png)
<img width="363" alt="screenshot at 22 04-27-57" src="https://user-images.githubusercontent.com/26658563/28487292-339c38a0-6e96-11e7-81ee-3a3e371b7207.png">
He is not world lines to dialogs (messages write random time)

**Comment by Eufranio** [comment]
Hmm, guess I'll have to add some extra checks to make sure the sender is a real player.

**Comment by Eufranio** [comment]
@PixelmonPRO, could you test with [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.8.1-all.jar)?

**Comment by PixelmonPRO** [comment]
@Eufranio works! Thanks!)
