### ISSUE TITLE
!Online, !List, !cmd all show in server chat

### ISSUE THREAD

**Issue by Asherslab** [Eufranio/MagiBridge#26]
pretty self-explanatory, basically when a user uses any of the discord commands they are displayed in the Minecraft server chat as well.

**Comment by Asherslab** [comment]
Hey, i've got a branch with this fixed ready to go now, i just need permissions to make a PR / branch =D

**Comment by Eufranio** [comment]
@Asherslab, you can open PRs just fine.

**Comment by Asherslab** [comment]
lol sorry, it'd be the fact that i can't push a new branch that'd be why =P i'm used to that way

**Comment by Eufranio** [comment]
Yea, you can push to master if it's a simple change.

**Comment by Eufranio** [comment]
@Asherslab, could you please test with [this](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.8.1-all.jar) build?

**Comment by Eufranio** [comment]
Assuming it's fixed.
