### ISSUE TITLE
[Idea] Support Discord @Tagging =D

### ISSUE THREAD

**Issue by Asherslab** [Eufranio/MagiBridge#29]
Just an idea, it would be nice if we could support @tagging from MC to Discord, so if someone tags @Asherslab in the server, it'll automatically tag them on Discord as well. it would also be nice if @Asherslabs-discord-nickname would work, but i'm not sure of the Discord API's limitations 😄

**Comment by Sade66** [comment]
I believe this already exists, not sure about nicknames though.

**Comment by Asherslab** [comment]
nope, i made this because he asked me to on discord

**Comment by kaal-1** [comment]
It would be cool if there was a permission node to allow users to tag others, and use @here and @everyone too. =)

**Comment by Eufranio** [comment]
@Asherslab and @kaal-1, could you please test [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.9.1-all.jar)?

**Comment by Eufranio** [comment]
Considering fixed.
