### ISSUE TITLE
Enhancement suggestions

### ISSUE THREAD

**Issue by kaal-1** [Eufranio/MagiBridge#3]
Just some ideas to help and improve the plugin:
- /discord bcast channel - Broadcast messages to discord channel
- /discord reload - Reload config files
- Broadcast minecraft achievements and death messages to discord
- Custom commands - For example, set !givevip %args% and run a set of commands.
- Show number of online players, TPS and ontime beside the discord servername. This message could change to something customizable like "Server offline" when the server shuts down.
- Some way to blacklist (or whitelist) channels in which you can use commands.

Thank you and sorry if any of these is already implemented. :)

**Comment by Eufranio** [comment]
* **/discord reload** isn't needed, MagiBridge reloads it's configs with **/sponge plugins reload**
* **Custom commands** don't fit in the plugin's purpose, I think. I mean, you can already send commands to the server using **!cmd (or whatever is defined in the config) <command>**, the Alias could be done with the [Aliases plugin](https://ore.spongepowered.org/me4502/Aliases) by example.
The other suggestions are nice, will take a look into implementing them :)

**Comment by Eufranio** [comment]
I think everything is done, will drop a pre-release soon.
