### ISSUE TITLE
Receive console MSGs in staff channel

### ISSUE THREAD

**Issue by Asherslab** [Eufranio/MagiBridge#30]
So currently when you use !cmd msg <player> <message> you don't see the response (As it's sent as "-" or "Server") it'd be nice if all the /msgs sent to the Server ("-") would output in the "staff" channel (so that normal players can't see it =D)

**Comment by Eufranio** [comment]
When using the console command, it DOES send the output of the command to the channel you used it.

**Comment by Asherslab** [comment]
Not the output, the player response from /msg

**Comment by Eufranio** [comment]
Plugins usually reply to the console instead replying to the atual command source, so there's no way to MagiBridge know what is a response and what is not. Sorry.

**Comment by Asherslab** [comment]
That's cool, just wasn't sure if you could filter just, /msgs or anything
