### ISSUE TITLE
Localization death messages

### ISSUE THREAD

**Issue by PixelmonPRO** [Eufranio/MagiBridge#31]
Hello! My public all Ru, and messages death in discord go in english.
How switch messages death in Ru language? In the game they are written in Russian.
<img width="431" alt="screenshot at 01 01-00-53" src="https://user-images.githubusercontent.com/26658563/28800368-12094784-7655-11e7-8f59-cca94809533c.png">

**Comment by Eufranio** [comment]
Actually, I can't just translate the messages to the selected lang, but I will once https://github.com/SpongePowered/SpongeAPI/pull/1224 is merged. We'll have to wait until this.

**Comment by PixelmonPRO** [comment]
This became possible with the plugin [Wasted](https://ore.spongepowered.org/Semenkovsky_Ivan/Wasted), i close issue)
