### ISSUE TITLE
Several issues and enhancements

### ISSUE THREAD

**Issue by Wadimich** [Eufranio/MagiBridge#32]
Hello!

I'm using LP, and prefix is colored, in discord, it looks like: _Bot &6[Admin] Wadimich: Проверка, раз раз_

I have custom launcher with HD skins support, webhook doesn't support them, looks weird.

Several enhancements:
I need a command to reload config from runtime.
Make additional access to !cmd for second/third discord group to specified commands in config. Like to allow moderators watch ingame chat and mute people, who talks bad.
Allow to translate this: _You don't have permission to use the console command!_
Allow to translate this: _There are no players online!_

**Comment by Eufranio** [comment]
Color codes in prefixes: test using [this](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.8.1-all.jar) build

Skins looking weird: there is no way for me to know what's the right skin. You can just disable the Webhook feature in the config. 

Reload: you can reload the plugin by using the /sponge plugins reload command. 

Additional access to the console command: I'll add this eventually, thanks for suggesting. 

No permission message: forgot to add this message to config :P

**Comment by Wadimich** [comment]
> Color codes in prefixes: test using this build

Didn't helped, still prints color code as is.

**Comment by Eufranio** [comment]
That does not make sense. Can you send a screenshot of how it looks like?

**Comment by Wadimich** [comment]
![screenshot](https://user-images.githubusercontent.com/21156193/28843234-df0772fa-7719-11e7-8693-89491e9ad593.png)
Take a look

**Comment by Eufranio** [comment]
Oh, I see the issue.

**Comment by Eufranio** [comment]
Please try now using [this](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.9.1-all.jar) build and let me know if it's fixed.

**Comment by Wadimich** [comment]
![screenshot](https://user-images.githubusercontent.com/21156193/28844077-e1f8d802-771c-11e7-82ae-2de25add528a.png)
Now it's fixed, i have orange prefix in game chat. Thanks for fast fix!

**Comment by Eufranio** [comment]
@Wadimich, would you like to test the new commands-role-override feature? As you suggested, now there is a way to give specific commands to specific roles. If you want to, test with [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.9.1-all.jar).

**Comment by Wadimich** [comment]
@Eufranio Error, 404 Not found :)

**Comment by Eufranio** [comment]
Oh... http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-2.0-all.jar

**Comment by Wadimich** [comment]
I've tested new feature. Works well, out moderators now can punish people even from smartphone :D

**Comment by Eufranio** [comment]
Great!
