### ISSUE TITLE
You can use colors via Dicord

### ISSUE THREAD

**Issue by PretoAlbino** [Eufranio/MagiBridge#34]
If you use &{color code} the message will be in the color you chose

**Comment by Eufranio** [comment]
@PretoAlbino, please test using [this](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-1.9.1-all.jar) build. Now, there is a field where you put the name of the role that using color codes will be allowed.
