### ISSUE TITLE
Have player list display prefixes properly

### ISSUE THREAD

**Issue by fcpwiz** [Eufranio/MagiBridge#35]
As of now, the list command displays the full, formatted prefix. Can MB take the name of the prefix/rank into %prefix%?

**Comment by Sade66** [comment]
To match the rest of the options, you'd want a `%topgroup&` option and a `%prefix%` option, just like WebHooks and messages.

**Comment by Eufranio** [comment]
Yea, have to add it soon.

**Comment by Eufranio** [comment]
%prefix% in the player list display is already a thing, I've added the %topgroup% placeholder to it.
