### ISSUE TITLE
Use display names instead group names in %topgroup%

### ISSUE THREAD

**Issue by fcpwiz** [Eufranio/MagiBridge#36]
As of now, LuckPerms does not provide a way to capitalize the first letter of a rank- nor to they intend on making it so. It would be amazing if MB could do this.

**Comment by Eufranio** [comment]
It can, take a look on group displaynames. MagiBridge should use them, so you can rename your groups for anything you want in the LP config.

**Comment by Sade66** [comment]
@Eufranio We did that and it didn't work.

**Comment by Eufranio** [comment]
The %topgroup% still showing the raw group name instead it's display name?

**Comment by Sade66** [comment]
Nope.. This is what our LP config looks like;

```
# Rewrites group names. The underlying name of the group does not change, just the output in commands / placeholders / Vault.
group-name-rewrite {
#  default="Member"
  owner="Owner"
  admin="Admin"
  moderator="Moderator"
  elite="Elite"
  expert="Expert"
  engineer="Engineer"
  builder="Builder"
  gatherer="Gatherer"
  amateur="Amateur"
  newbie="Newbie"
}
```

**Comment by Eufranio** [comment]
Waiting for LuckPerms: https://github.com/lucko/LuckPerms/issues/412, since I won't be supporting 2 MagiBridge versions just to use the Sponge's method. It will be a LP-only feature too.

**Comment by Eufranio** [comment]
@Sade66 and @fcpwiz, could you test using [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-2.0.2-all.jar)? Now it should be getting the LuckPerms' group display name, if available. You will need latest LP.

**Comment by Sade66** [comment]
@Eufranio We will try this, thanks! :)

_Sent from my Motorola XT1585 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
