### ISSUE TITLE
Skins not rendering properly with webhooks

### ISSUE THREAD

**Issue by Wadimich** [Eufranio/MagiBridge#37]
I've set my skin to standart skin size, downloaded from ely.by (custom auth system and skin system).
This is how this skill looks:
![1wh07ro](https://user-images.githubusercontent.com/21156193/28871960-60b262ca-77a0-11e7-93a0-6a08c1f7599e.png)

**Comment by Eufranio** [comment]
The skins are NOT rendered, the Webhook image is the WHOLE image, not the skin, like this: https://crafatar.com/avatars/PotterCraft_

If you want only the head to be displayed in the image, you will need the link of an API that provides the exact and only the head as image. The default API (can be changed in the config) is Crafatar, it works for standard skins (from Mojang). If you want to use a custom skin service, you're on you own.

**Comment by Wadimich** [comment]
Oh, okay, understood, thanks!
