### ISSUE TITLE
MagiBridge Commands no response

### ISSUE THREAD

**Issue by focus17** [Eufranio/MagiBridge#39]
After installing, Chat portal works fine, but commands are unresponsive. Plz help
https://i.gyazo.com/804c66efba7c4aeec5d7277a7051d8c8.png

**Comment by Eufranio** [comment]
Please send your fml-server-latest.log.

**Comment by focus17** [comment]
Thank you for taking the time
https://i.gyazo.com/f99dcb237bc6a8e5aafc6b762e97d3ef.png
https://mega.nz/#!qUEHmZQL!tZYBLDdiHAv5Pr-cmUd7sAocnVCpAT0dKBbAb7kbpsk

**Comment by Eufranio** [comment]
Please post it in pastebin or gist...

**Comment by focus17** [comment]
https://gist.github.com/focus17/2cd24942fd99205907a0ef35dca04ab7

**Comment by Eufranio** [comment]
Fill the config with the channel IDs, like the main and global channels, because you didn't yet. Also, `Cannot perform action due to a lack of Permission. Missing permission: MESSAGE_MANAGE`, give your bot the MANAGE MESSAGES permission.

**Comment by focus17** [comment]
I thought the those ID's were unnessisarry because im using UChat, but ill do that. Thanks

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
