### ISSUE TITLE
Enhancement for commands and display name

### ISSUE THREAD

**Issue by kaal-1** [Eufranio/MagiBridge#40]
It would be nice if there was an option to disable the feature that deletes the !cmd and !online messages, as well as an option to customize how long, in seconds, it takes for these messages to be deleted. I think the !cmd response should be deleted as well, if this feature is enabled. :)

Also, I think there should be a placeholder to get the nucleus /nick (without the formatting of course), and if it is not set, return the real username instead. This way it would be possible to change the webhook name to something like %nick% (%realname%) or simply %nick%.

**Comment by Eufranio** [comment]
@kaal-1, could you please test [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-2.0.2-all.jar)? You can now disable deleting messages and use the nick placeholder on the UChat hook messages.
