### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by PixelmonPRO** [Eufranio/MagiBridge#43]
Hello! I update 2.0.1 to 2.0.2 and have next error in console:
<img width="1088" alt="screenshot at 01 02-35-48" src="https://user-images.githubusercontent.com/26658563/29949584-767e27c6-8ebe-11e7-9155-927da0cb3706.png">
Config: https://gist.github.com/PixelmonPRO/d89130a9322762d364f67265b461df7b

**Comment by Eufranio** [comment]
Try using [this build](http://ci.heyzeer0.cf/job/MagiBridge/lastSuccessfulBuild/artifact/build/libs/MagiBridge-2.0.2-all.jar).

**Comment by PixelmonPRO** [comment]
Thanks, everything works as it should :)
