### ISSUE TITLE
Error on startup - API 7

### ISSUE THREAD

**Issue by merjilin** [Eufranio/MagiBridge#49]
Hey, Eufranio!

Recently installed this on my API 7 test server, and on startup, this error pops up. This seems to result in no startup message being relayed to discord.

https://gist.github.com/merjilin/c3387a53c31945b68b44cb34fe044c6d

**Comment by Eufranio** [comment]
You should use the API7 jar file, you're using the wrong one. Check the releases section.

**Comment by merjilin** [comment]
Oh bugger! So very sorry. I misread the note at the bottom.
