### ISSUE TITLE
[1.10.2-1.12.2] Achievements and Advancements not showing up on Discord. 

### ISSUE THREAD

**Issue by KaneHart** [Eufranio/MagiBridge#52]
Both 1.10.2 and 1.12.2 Versions of the plugin does has never displayed achievements / advancements in discord not even vanilla ones. 

**1.12.2:**
forge-1.12.2-14.23.1.2566-universal.jar
spongeforge-1.12.2-2555-7.0.0-BETA-2774.jar
MagiBridge-API7-2.4.2.jar

**1.10.2:**
forge-1.10.2-12.18.3.2477-universal.jar
spongeforge-1.10.2-2477-5.2.0-BETA-2731.jar
MagiBridge-2.4.2.jar

**Both Configs:**
    # Should MagiBridge send achievement get messages to Discord?
    achievement-messages-enabled=true

**Comment by Eufranio** [comment]
As for 1.12, advancements/achievements aren't implemented yet on Sponge. For 1.10.2, something on Sponge broke the event, so it isn't being fired anymore (not sure why), but I'll open an issue there for it.

**Comment by Eufranio** [comment]
Edit: looks like the event was implemented only on 1.11.2, then removed due to the advancements. Sorry.
