### ISSUE TITLE
Feature Request: Icon game

### ISSUE THREAD

**Issue by PixelmonPRO** [Eufranio/MagiBridge#55]
Hello! Can you add icon for the game / custom text to the bot?
Example:
<img width="189" alt="2018-01-13 1 48 54" src="https://user-images.githubusercontent.com/26658563/34898409-ff075834-f803-11e7-912c-ed8bd35700f7.png">
(https://minecraft.curseforge.com/projects/discordsuite //but is mod for players, no server)

**Comment by Eufranio** [comment]
This is called Rich Presence, but is only usable by users (not bots), so I cannot implement it.
