### ISSUE TITLE
Don't receive ingame messages in Discord

### ISSUE THREAD

**Issue by Elite82pt** [Eufranio/MagiBridge#57]
Hey there I'm running your plugin in my server and I'm having this issue where I don't see the messages sent in game. I can send from Discord to MagiBridge but not from Magibridge to Discord...Maybe It's something simple and I'm just very noob. BTW I'm using Ultimate Chat.

Thanks

**Comment by Eufranio** [comment]
Your players need permission to chat in the UltimateChat channel, and your channels should be linked correctly in the UltimateChat config section.
