### ISSUE TITLE
default setting for webhook-picture-url required UUID, not player name

### ISSUE THREAD

**Issue by iamtpage** [Eufranio/MagiBridge#59]
Hi,

The default setting for `webhook-picture-url` requires the player's UUID, not the player's name. Currently the setting only supports `%player%` (which i assume is just the player's name as it is used in other parts of the config). 

Can you add support for `%uuid%`?

Source: https://crafatar.com/#meta-usernames

**Comment by Eufranio** [comment]
Will do. Actually, %player% is the player name.

**Comment by Eufranio** [comment]
Should be fixed by https://github.com/Eufranio/MagiBridge/commit/6fcf379e89bd9344cabcfab46f021f2c99374355. Download the latest build from Ore.
