### ISSUE TITLE
Nucleus + Luckperms + Magibridge, Ingame chat not being forwarded to discord.

### ISSUE THREAD

**Issue by eddoww** [Eufranio/MagiBridge#62]
[05:35:16] [Server thread/ERROR] [Sponge]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=magibridge, name=MagiBridge, version=2.4.5.1, description=A utility Discord <-> Minecraft chat relay plugin, authors=[Eufranio], source=C:\Users\vevion\Desktop\Modern Skyblock\mods\MagiBridge-API7-2.4.5.1.jar}
net.dv8tion.jda.core.exceptions.ErrorResponseException: 400: {"name":["Must be between 2 and 32 in length."]}
        at net.dv8tion.jda.core.exceptions.ErrorResponseException.create(ErrorResponseException.java:145) ~[ErrorResponseException.class:?]
        at net.dv8tion.jda.core.requests.Request.onFailure(Request.java:82) ~[Request.class:?]
        at net.dv8tion.jda.core.requests.restaction.WebhookAction.handleResponse(WebhookAction.java:98) ~[WebhookAction.class:?]
        at net.dv8tion.jda.core.requests.Request.handleResponse(Request.java:164) ~[Request.class:?]
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:198) ~[Requester.class:?]
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:108) ~[Requester.class:?]
        at net.dv8tion.jda.core.requests.Requester.execute(Requester.java:91) ~[Requester.class:?]
        at net.dv8tion.jda.core.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:314) ~[BotRateLimiter$Bucket.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_144]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) ~[?:1.8.0_144]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_144]
        at net.dv8tion.jda.core.requests.RateLimiter$RateLimitThreadFactory.lambda$newThread$0(RateLimiter.java:105) ~[RateLimiter$RateLimitThreadFactory.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]

**Comment by Eufranio** [comment]
Can you send your config? Make sure to hide your token.

**Comment by eddoww** [comment]
Default config aside from changed token & channel/server ID.

**Comment by IchigoGames** [comment]
i have the opposite issue using Luckperms + Magibridge discord chat is not being forwarded to minecraft

**Comment by eddoww** [comment]
`# MagiBridge, by Eufranio
# 
# You can use the following placeholders on the DISCORD -> MC formats:
# %user% -> user who sent the message in the Discord channel
# %message% -> message that was sent to the channel
# %toprole% -> name of the highest role/rank of the user in the Discord server
# %toprolecolor% -> color of the user's role, according to the replacer at the bottom of this config
# 
# You can use the following placeholder on the MC -> DISCORD formats:
# %player% -> player who sent the message in the chat channel
# %prefix% -> prefix of the player that sent the message. Usually set via permission plugins
# %topgroup% -> name of the highest group of the player who sent the message
# %nick% -> nickname of the player. If no nick is assigned to the player, his name will be used instead
# %message% -> message that the player sent

channel {
    # Role that users need to have to be able to send colored chat to minecraft
    # Set to "everyone" to allow everyone use colors in the messages
    color-allowed-role=vip
    # If a command is defined here, it will ONLY run if the user has the defined role.
    # In this example, ONLY who have the admin role can stop the server
    # Set the role to "everyone" to allow everyone use the command
    commands-role-override {
        ban=mod
        stop=admin
    }
    # Discord command that executes server console commands
    console-command="!cmd"
    # Role that a user needs to have in order to run the console command
    console-command-required-role=admin
    # Should MagiBridge delete the player list message?
    delete-list-message=true
    # ID of the main Discord Channel, where start/stop messages will be sent to
    main-discord-channel="377952873150939136"
    # IGNORE IF USING ULTIMATECHAT!
    nucleus {
        # Discord Channel ID which global messages are sent to
        global-discord-channel="377952873150939136"
        # Discord Channel ID which messages from the staff chat are sent to
        staff-discord-channel="370728801577074692"
    }
    # Discord command that shows the current online player list
    player-list-command="!online"
    # IGNORE IF USING NUCLEUS!
    ultimatechat {
        # Channels defined here override the global format, so you can have per-channel formats
        channel-overrides {
            global="&7[&a&lG&7] &f%user%&7: %message%"
        }
        # Format: ChannelID = IngameChannelName, Example:
        # 12345678912345 = global
        # Replace the default value with your own channels
        channels {
            "12345678912345"=global
        }
    }
    # Should MagiBridge use Nucleus? If this and use-ultimatechat are both false, MagiBridge will use the vanilla chat system
    use-nucleus=true
    # Should MagiBridge use UltimateChat instead? If this and use-nucleus are both false, MagiBridge will use the vanilla chat system
    use-ultimatechat=false
    # Should MagiBridge send messages trough Webhooks instead a bot?
    use-webhooks=true
}
colors-converter {
    # Conversor from RGB to in-game colors (for %toprolecolor%)
    # Format: "RGB" = "IN-GAME COLOR"
    discord-to-mc-replacer {
        "206694"="&1"
        "11806A"="&2"
        "1ABC9C"="&a"
        "1F8B4C"="&2"
        "2ECC71"="&a"
        "3498DB"="&3"
        "546E7A"="&8"
        "607D8B"="&8"
        "71368A"="&5"
        "95A5A6"="&7"
        "979C9F"="&7"
        "992D22"="&4"
        "99AAB5"="&f"
        "9B59B6"="&5"
        A84300="&6"
        AD1457="&d"
        C27C0E="&6"
        E67E22="&6"
        E74C3C="&c"
        E91E63="&d"
        F1C40F="&e"
    }
}
core {
    # Should MagiBridge send achievement get messages to Discord?
    achievement-messages-enabled=true
    # Bot Token of the Bot User that you want to be used when sending messages to Discord
    bot-token="123456"
    # Set to false if MagiBridge should NOT cut messages coming from Discord with more than
    # 120 characters. This can turn the chat ugly if someone sends a big message
    cut-messages=false
    # Should MagiBridge send death messages to Discord?
    death-messages-enabled=true
    # Should MagiBridge enable the Topic Updater, updating the topic of the main Discord channel?
    enable-topic-updater=true
    # Don't send messages of a player to Discord if he is vanished
    hide-vanished-chat=false
    # Topic Updater interval in seconds, minimum is 10
    topic-updater-interval=10
    # Should MagiBridge enable Boop support? Will only work if Boop is installed and updated
    use-boop=false
}
discord-to-mc-replacer {
    # Text that will be replaced in messages sent TO the game
    # Format: "word-to-replace" = "word-replaced"
    discord-to-mc-replacer {
        ":dizzy_face:"=xO
        ":frowning:"=":("
        ":heart:"="<3"
        ":joy:"=";D"
        ":kissing:"=":*"
        ":laughing:"=xD
        ":neutral_face:"=":|"
        ":open_mouth:"=":O"
        ":smile:"=":D"
        ":smiley:"=":)"
        ":sob:"=";("
        ":stuck_out_tongue:"=":P"
        ":stuck_out_tongue_closed_eyes:"=xP
        ":stuck_out_tongue_winking_eye:"=";P"
        ":sunglasses:"="B)"
        ":tired_face:"="x("
        ":wink:"=";)"
    }
}
messages {
    # Message that will be sent to the main discord channel when a player grants a achievement
    # Supports %achievement%
    achievement-message="**%player% got a new achievement: %achievement%**"
    # Messages sent to Discord when a player goes/retuns AFK, if enabled
    afk {
        enabled=false
        # Message sent when a player goes AFK
        going="%player% is now AFK"
        # Message sent when a player is not AFK anymore
        returning="%player% is not AFK anymore"
    }
    # Name of the attachment tag shown in-game when someone sends an attachment to the Discord channel
    attachment-name="[Attachment]"
    # Game that will be displayed in the bot's game status
    bot-playing-status="Playing on a nice server!"
    # Message that will be set in the main discord channel topic every X seconds
    # Supports %tps%, %players%, %maxplayers%, %hoursonline% and %minutesonline%
    channel-topic-message="%players%/%maxplayers% players online | TPS: %tps% | Server online for %hoursonline% hours or %minutesonline% minutes!"
    # Message that will be set in the main discord channel topic when the server goes offline
    channel-topic-offline="The server is currently offline!"
    # No permission message (for console command)
    console-command-no-permisson="**You don't have permission to use this command!"
    # Message that will be sent to the main discord channel when a player dies
    death-message="**Bad day for %player%: %deathmessage%**"
    # Format of the messsage sent from Discord to the server
    discord-to-server-format="&f%user%&7: &7%message%"
    # Format of the messages sent from the Discord Staff channel to the server
    # Node: This format is used ONLY when using the Nucleus hook!
    discord-to-server-staff-format="&f%user%&7: &7%message%"
    # Message that will be sent to the main discord channel when a new player joins the server
    new-players-message="**Enjoy playing on our server, %player%!**"
    # Message shown when there are no players in the server 
    # and the list command is executed
    no-players-message="**There are no players online!**"
    # Text that will be used in %toprole% when the user don't have any roles (besides @everyone)
    # Use only if you need. If you don't, leave this option as ""
    no-role-placeholder=""
    # Message that will be sent to the discord-main-channel when a player joins the server
    player-join-message="**%player%** joined the server"
    # Format of the player name displayed in the channel list command (!online)
    player-list-name="%player%"
    # Message that will be sent to the discord-main-channel when a player leaves the server
    player-quit-message="**Bye, %player%!**"
    # Prefix that will be sent before the actual message, with a hover and clickable link
    prefix {
        enabled=true
        hover="&bClick do join our Discord!"
        link="https://discord.gg/mnUpmMP"
        text="&6[Discord]"
    }
    # Message that will be sent to the discord-main-channel when the server starts
    server-starting-message="**The server is starting!**"
    # Message that will be sent to the discord-main-channel when the server stops
    server-stopping-message="**The server is stopping!**"
    # Format of messages sent FROM the server TO discord
    server-to-discord-format="**%player%**: %message%"
    # Format of messages sent FROM the server staff channel TO the discord staff channel
    # Used only when Nucleus is running and enabled
    server-to-discord-staff-format="**%player%**: %message%"
    # Format of the name of the webhooks that will send messages to Discord, if enabled
    webhook-name="[%prefix%] %player%"
    # URL that webhooks should get the skin picture from
    # Note: the link SHOULD return a valid .png picture from the request!
    # Supports %player%
    webhook-picture-url="https://crafatar.com/avatars/%uuid%?default=MHF_Alex"
}
`

**Comment by Cebtenzzre** [comment]
Based on the fact that BotRateLimiter is in the stack trace, I feel like this could be an upstream issue with JDA.  But I could be wrong, it could also just be that a value gets passed around and down _really deep_.

@eddoww If you can still reproduce this issue, can you get a more detailed stack trace?  If you can set up [stackparam](https://github.com/cretz/stackparam), the actual issue would show itself better (though I _believe_ it's trying to send a webhook message with an empty name).

And I suppose the usual idea of building the latest git master and testing it applies, but I doubt it'll change much.

**Comment by Eufranio** [comment]
Maybe the webhook name (`[%prefix%] %player%`) was too long? That could be caused by a long prefix + player name. Can you try leaving `webhook-name` as `%player%` only?

**Comment by quikenb** [comment]
Just to update on this. It seems that Eufranio was right and what I have had figured that when used with luckperms, the [%prefix%] placeholder crashes with the prefix from luckperms. If you remove the [%prefix%] from the config file, the prefix will still remain next to the user in the discord chat. For future issues I have just spent 2 days trying to figure this out and finally did. And remember, always give your bot perms eddoww
