### ISSUE TITLE
Problem chat

### ISSUE THREAD

**Issue by slitesun** [Eufranio/MagiBridge#64]
Messages get lost on the way from minecraft to discord channel.

log of error: https://pastebin.com/c5vv9HZk
version plugin: 2.4.5.1
version sponge: spongeforge-1.10.2-2477-5.2.0-BETA-2793.jar

**Comment by Eufranio** [comment]
Use the version 2.4.5, as the v2.4.5.1 is ONLY for 1.12+. Read the changelog.

**Comment by slitesun** [comment]
Thank you
