### ISSUE TITLE
Main thread goes waiting state because of magibridge

### ISSUE THREAD

**Issue by XakepSDK** [Eufranio/MagiBridge#67]
https://puu.sh/A8ipS/50957dd9ff.png
First green line - main thread.
Netty epoll server - netty client serving threads

**Comment by XakepSDK** [comment]
https://puu.sh/A8jwi/5979bec24e.png
https://puu.sh/A8jwK/72ea57c0d8.png

**Comment by Eufranio** [comment]
Fixed that.
