### ISSUE TITLE
How to get chat message FROM Discord to show up IN the Minecraft client?

### ISSUE THREAD

**Issue by vorburger** [Eufranio/MagiBridge#71]
I managed (see #69 and #70) to see messages typed in the Minecraft chat in the Discord channel.

When I type a message in Discord, it shows on the Minecraft server console, but not in the Minecraft client:

    [16:29:10 INFO]: michaelpapa7: hey
    [16:29:44 INFO]: [Discord]anorak: yo

what set up / configuration am I missing to get that to go through? Using Nucleus here BTW, if related.

**Comment by vorburger** [comment]
bennyb1971 in #support dixit:

> I had to give my players nucleus.staffchat perms and then the messages show up

**Comment by vorburger** [comment]
bennyb1971 in #general dixit:

> its a permissions issue, i had to add nucleus.home.limit.base as permission to my default group

**Comment by vorburger** [comment]
AzureZhen on #support dixit:

> You are likely adding in the staff channel ID as the same channel as your normal chat, that would cause the issue as it would be sending messages to the staff chat instead the normal chat. You can either leave that part blank, creating a different channel for that, or just giving the permission as stated.

and that was indeed it for me - I DID put the same channel in all x3 places... when blank, it works!

Perhaps the inline documentation in `MagiBridge.conf` could be updated to clarify this?

**Comment by Eufranio** [comment]
The main channel can yes be the same as the staff channel. People should read the config before filling it with random values. The staff channel being set to the same channel as the main one implies that the user must be able to write on both, hence the permission check.
