### ISSUE TITLE
Integrated Minecraft / Discord user identity?

### ISSUE THREAD

**Issue by vorburger** [Eufranio/MagiBridge#72]
If I understand correctly, currently the Minecraft and Discord user identity are completely separate, right?

Is there any way to have them single signed on / aligned? Or do folks just use the same name by convention?

**Comment by Eufranio** [comment]
MBDiscordLink is a separated plugin, it links minecraft accounts to discord accounts and does some cool stuff, but it doesn't merge the 2 identities. Discord users still discord users and are displayed as that, and the same goes for minecraft users. MBDiscordLink doesn't change the displayed info of any of them.
