### ISSUE TITLE
Release binary JAR also on github.com not just on Ore?

### ISSUE THREAD

**Issue by vorburger** [Eufranio/MagiBridge#73]
I've noticed that up to v2.4.2, you published the binary JAR on github.com at https://github.com/Eufranio/MagiBridge/releases, but for v2.4.5 you only provide the sources, with the binary JAR now only on https://ore.spongepowered.org/Eufranio/MagiBridge.

Was wondering if this was intentional or just an oversight? The trouble with Ore is that, as far as I can see, it's [not possible to have an automated script DL from Ore](https://github.com/OASIS-learn-study/swissarmyknife-minecraft-server/blob/0246b6b4591e41ab26e908257d21165109679d07/.s2i/bin/assemble) - there is some token thing that keeps changing.

**Comment by vorburger** [comment]
In the mean time, I'll just build it from source as part of that script, instead of DL a binary JAR...

**Comment by Eufranio** [comment]
Ore is the most suitable place for MagiBridge distribution right now for me and my current setup. You should still be able to download jars from Ore, I did it personally once...
