### ISSUE TITLE
Remove bundled native code

### ISSUE THREAD

**Issue by vorburger** [Eufranio/MagiBridge#80]
when I had a closer look at the JAR (in the context of #76), I noticed that it includes a number of native libraries. Those appear to be coming in transitively from https://github.com/DV8FromTheWorld/JDA/tree/master/src/main/resources/natives and seem to be used via JNA for https://github.com/DV8FromTheWorld/JDA/tree/master/src/main/java/tomp2p/opuswrapper, which -unless this plugin also records audio ;-) which I'm sure is not the intention- can be removed from the shadow packing.

This also quite significantly reduces the size of the JAR - from ca. 9 MB down to under 7 MB.

**Comment by Eufranio** [comment]
Thanks for the PR.
