### ISSUE TITLE
I have a question...

### ISSUE THREAD

**Issue by EnderGamingFilms** [Eufranio/MagiBridge#82]
So with UChat discord integration, it adds a little "Online: 0" section under my bot. Does MagiBridge have the same functionality as uchat discord integration?

Example:
https://imgur.com/Gfc3zii.png

**Comment by Eufranio** [comment]
MagiBridge can edit the channel topic with the TPS, uptime and online player count (its called topic updater).

**Comment by EnderGamingFilms** [comment]
So that is a "No" on can this plugin add the player count under the bots name.

**Comment by Eufranio** [comment]
Yep.
