### ISSUE TITLE
MagiBridge + UC channel config issue

### ISSUE THREAD

**Issue by Lyl4c** [Eufranio/MagiBridge#84]
Client is using vanilla 1.12.2
Server:
minecraft 1.12.2
forge 14.23.4.2705
sponge 2705-7.1.0-BETA-3151
MagiBridge API7-2.4.5.1
UltimateChat 1.8.5-b151

Magi config: https://pastebin.com/9DcGvVgx
bagel-zero channel config: https://pastebin.com/iL6KdaNV
lucidstuck channel config: https://pastebin.com/bFaChZPE

I can't get magibridge to recognize the custom channels put into its config. Those channels are not showing up in game when I use /ch list . I am following the documentation found inside the server side configs and it seems obvious about what to do there, but I am missing something. At one point after inputting incorrect values for custom channels; the whole magi config file had deleted itself.

**Comment by Eufranio** [comment]
If the channels aren't showing in-game when listing the channels, this is most likely a problem with your UltimateChat configs, not with MagiBridge.
