### ISSUE TITLE
MagiBridge Won't Connect to Discord

### ISSUE THREAD

**Issue by Sade66** [Eufranio/MagiBridge#85]
I have gone through and setup our configs, and I'm getting [this error](https://gist.github.com/Sade66/6bda7593e4466dab72e667803702b525) when the server starts. My Sponge version is **spongeforge-1.12.2-2705-7.1.0-BETA-3151** and my I'm on Minecraft **1.12.2**.

**Comment by Asherslab** [comment]
It does say at the top of that crash:
`Error connecting to discord. This is NOT a plugin error`

**Comment by Sade66** [comment]
I'm aware of that. I was hoping @Eufranio would be able to clarify what exactly is causing the error.

**Comment by Asherslab** [comment]
Has your server got an outgoing internet connection?
Is your firewall setup in such a way that it'd block connections from the server to external (port 80/443 specifically)

**Comment by fcpwiz** [comment]
Fixed by letting the config regenerate, there was a JSON formatting issue.
