### ISSUE TITLE
Name showing up twice in chat.

### ISSUE THREAD

**Issue by ZiroGX2** [Eufranio/MagiBridge#86]
![image](https://user-images.githubusercontent.com/22279426/41884326-f5290446-78c0-11e8-905b-adcd721e8829.png)

**Comment by meredithdoto** [comment]
This is probably related to your chat formatting plugin

**Comment by ZiroGX2** [comment]
Nucleus

**Comment by meredithdoto** [comment]
Than you should ask on nucleus git / discord. On 100% its not MagiBridge issue!
Try change something in _chat_ section in `main.conf` file.
In my opinion it's `check-body-for-minecraft-prefix=true` what should fix issue

**Comment by Eufranio** [comment]
As @meredithdoto said, this is not a MagiBridge issue.
