### ISSUE TITLE
[REQUEST] HelpOp from Nucleus displayed in discord chat

### ISSUE THREAD

**Issue by meredithdoto** [Eufranio/MagiBridge#87]
Hi, our staffs like staff chat very much. It's cool feature better than just general chat (which spam chat on discord or vise versa) But in our opinion if staffs aren't in game they can still help with issues.

**Comment by Eufranio** [comment]
I dont get the issue nor your suggestion. You want help op messages to show on Discord?

**Comment by meredithdoto** [comment]
Yes, I said that in topic [REQUEST] HelpOp from Nucleus displayed in discord chat #87

**Comment by Eufranio** [comment]
So?

**Comment by meredithdoto** [comment]
Yes I want see message from Helpop on discord

**Comment by Eufranio** [comment]
Ok, I think I got it.

**Comment by meredithdoto** [comment]
Thanks

**Comment by Eufranio** [comment]
Please test using the latest MagiBridge version: https://ore.spongepowered.org/Eufranio/MagiBridge/versions
