### ISSUE TITLE
MagiBridge stops server from stopping after crash

### ISSUE THREAD

**Issue by DiamondArrow** [Eufranio/MagiBridge#88]
When my server crashes, sometimes it would spam this instead of stopping:
https://pastebin.com/raw/N86pH1GT

I was told that this may be an issue with MagiBridge

using 
MagiBridge-API7-2.4.5.1
spongeforge-1.12.2-2705-7.1.0-BETA-3206

**Comment by Eufranio** [comment]
It should not deny your server from stopping, but yea that looks like a problem with MagiBridge. I'll take a look on it soon.

**Comment by Eufranio** [comment]
Please test using the latest MagiBridge version: https://ore.spongepowered.org/Eufranio/MagiBridge/versions
