### ISSUE TITLE
gradlew is not marked executable

### ISSUE THREAD

**Issue by Cebtenzzre** [Eufranio/MagiBridge#89]
On a POSIX system like mine (specifically Arch Linux), there is some work needed before the gradle wrapper can be run: Setting the executable bit on gradlew with `chmod +x gradlew`.

Please mark gradlew as executable with `git update-index --chmod=+x gradlew`, so that people on _standardized_ OSes (MacOS, Linux, BSD, etc.) -- particularly Linux, which Linus Torvalds wrote Git for in order to make development of the kernel easier -- can more conveniently build this plugin.

**Comment by vorburger** [comment]
@Cebtenzzre how about contributing to this very cool project by raising a small PR with this, for @Eufranio to review and merge?

**Comment by Cebtenzzre** [comment]
I figured the change was small enough to not be worthy of a PR, but alright, I'll make one.
