### ISSUE TITLE
LuckPerms, #console, & webhooks

### ISSUE THREAD

**Issue by fcpwiz** [Eufranio/MagiBridge#9]
Some features I'd love to see:

- [x] 1. Have the IGN LuckPerms ranks display in front of name in Discord chat. (ex. "[Newbie] fcpwiz: Hey guys!")

- [ ] 2. Have a #console channel on Discord that displays the console output and that can be interacted with.

- [x] 3. Have option to use webhooks for players so IGN player skin and name are viewable from Discord.

Thanks!

**Comment by Eufranio** [comment]
How should I deal with the **%prefix%** placeholder when the message is sent via webhooks (use-webhooks option enabled)?

**Comment by fcpwiz** [comment]
Hmm, good question.

I'd throw the prefix in front of the username of the "bot." Know what I mean?

**Comment by Eufranio** [comment]
Yea, gess I'll add a placeholder for the webhook name.

**Comment by fcpwiz** [comment]
@Eufranio And how often will it check for prefixes? Like if a player ranks up, how long will it take to recognize the change?

**Comment by Eufranio** [comment]
I'm hooking into Sponge, it will take the player's current prefix in account, so the prefix time/whatever is handled by the permissions plugin (such as LuckPerms).

**Comment by fcpwiz** [comment]
@Eufranio Gotcha. Also, check out this MagiBridge logo I'm messing with: 

![magibridge2](https://user-images.githubusercontent.com/2921172/28249843-c20b2c46-6a2b-11e7-9f4f-02b6da285461.png)

**Comment by Eufranio** [comment]
That looks amazing, thanks!

**Comment by fcpwiz** [comment]
Yep!

Do these two commits complete feature 1?

**Comment by Eufranio** [comment]
No, only in webhooks, will add in bot messages too.

**Comment by Eufranio** [comment]
Yea.

**Comment by Eufranio** [comment]
Console logging will take some time, I'll drop a new release and take a look on it later.

**Comment by fcpwiz** [comment]
Awesome! Once you have that feature, my team is switching over :)

**Comment by fcpwiz** [comment]
@Eufranio Just added a 4th feature

**Comment by Eufranio** [comment]
Hmm, what do you mean by `display Discord rank when viewing ingame MC chat`?

**Comment by fcpwiz** [comment]
PlayerX is a moderator of a discord server and has the moderator rank in Discord.
PlayerY is a player in-game, viewing the chat.

PlayerX types "hey, what's up guys?" via Discord.
PlayerY sees: `{DC} [Moderator] PlayerX: hey, what's up guys?`

**Comment by Eufranio** [comment]
Hmm, it's covered by https://github.com/Eufranio/MagiBridge/issues/7

**Comment by fcpwiz** [comment]
What does %toprole% mean, exactly?

**Comment by Eufranio** [comment]
**Role** is how we call your discord "rank". **%toprole%** will display the name of the highest "rank" that a discord user has.

**Comment by fcpwiz** [comment]
Ahh gotcha, redacting my request :)

**Comment by fcpwiz** [comment]
Added 2 new requests, per my server partner.

**Comment by Eufranio** [comment]
I'm focusing in the other issues, please open a new ticket for features, or this one will become filled with comments...

**Comment by Eufranio** [comment]
The console channel is not going to be added.
