### ISSUE TITLE
Doesnt work with latest version of spongeforge

### ISSUE THREAD

**Issue by ZaosDaOne** [Eufranio/MagiBridge#93]
i updated to the latest sponge forge (3266) and it no longer works like completely just doesnt work

**Comment by Eufranio** [comment]
That was probably due to Sponge's Configurate, which was fixed (https://github.com/SpongePowered/configurate/issues/113). Can you test again and, if it's not fixed, can you provide me the stacktrace/log?

**Comment by Eufranio** [comment]
The latest recommended build of Sponge should fix those issues. Update if you haven't already.
