### ISSUE TITLE
[Suggestion] Disable @everyone from carrying through to webhooks

### ISSUE THREAD

**Issue by DiamondArrow** [Eufranio/MagiBridge#94]
AFAIK there's no way to disable @everyone and @here mentions for webhooks on Discord which means any player on the server can ping everyone. It'd be nice to alter or deny those messages from being transmitted to Discord

**Comment by Asherslab** [comment]
you can, via discord permissions. Disable the bot from using the @everyone or @here pings.

**Comment by DiamondArrow** [comment]
@Asherslab disabling the bot perms doesn’t seem to affect webhooks

**Comment by Eufranio** [comment]
Do your players have the `magibridge.everyone` permission?

**Comment by DiamondArrow** [comment]
Players do not have magibridge.everyone and I made sure the bot doesn't have mention everyone perm
![image](https://user-images.githubusercontent.com/7917826/42534898-ce0a48c4-8442-11e8-843d-609e5ec89eda.png)

**Comment by Eufranio** [comment]
Okay, I'll review the code again then.

**Comment by DiamondArrow** [comment]
Update: Disabled Webhooks option in magibridge conf and now @everyone and @here is removed before msg is sent to Discord. I'm guessing that's how it was intended to work

**Comment by Eufranio** [comment]
Please test using the latest MagiBridge version: https://ore.spongepowered.org/Eufranio/MagiBridge/versions
