### ISSUE TITLE
Webhooks causing server timeouts

### ISSUE THREAD

**Issue by popcorn1111** [Eufranio/MagiBridge#95]
Our server was having timeout issues. Upon further inspection using Spark, I believe the issue is related to webhooks. I captured the full tree below:

https://gyazo.com/45c60b2ee791cccdc095d1b5ddf90934
https://gyazo.com/bb1e23a98c93bbefdff1f573d960f831

**Comment by Eufranio** [comment]
Please test using the latest MagiBridge version: https://ore.spongepowered.org/Eufranio/MagiBridge/versions
