### ISSUE TITLE
[Suggestion] Make a permission for @'ing players

### ISSUE THREAD

**Issue by popcorn1111** [Eufranio/MagiBridge#96]
Similar to the magibridge.everyone permission, I was wondering if a permission could be added to control @'ing players in general. For our server specifically, it would help since normal players like to @ admins for non-admin related issues. Giving this permission to staff only would ensure we were not pinged unnecessarily. Not the biggest thing, but would be nice in the future.

**Comment by Eufranio** [comment]
I've just added a `magibridge.mention` permission (granted by default) to mention players in the latest version of MagiBridge.
