### ISSUE TITLE
The main-discord-channel is INVALID, replace it with a valid one and restart the server!

### ISSUE THREAD

**Issue by iamtpage** [Eufranio/MagiBridge#97]
Been loving this plugin, however after upgrading to the latest version the plugin causes the server to time out with a massive spam about how the main-discord-channel is invalid (despite being previously connected to it)

Gist: https://gist.github.com/iamtpage/75e63129eda96d552ce339b71ab16eb0

**Comment by Asherslab** [comment]
It's not the plugin, it's JDA

**Comment by Eufranio** [comment]
I don't have much to do for now, sorry.
