### ISSUE TITLE
[Suggestion] Add a license

### ISSUE THREAD

**Issue by DoNotSpamPls** [Eufranio/MagiBridge#99]
Currently the plugin doesn't have any LICENSE file, which means it's All rights reserved (a.k.a. nobody has the permission to even edit the code). You can choose the right license for you over at https://choosealicense.com

**Comment by vorburger** [comment]
@Eufranio this would indeed be very very useful to clarify. If you are unclear about why you really really should be adding a license at all, or which specific license to choose, then ask here and perhaps those of us using your (great, thanks!) plugin can help guide... For example, the Sponge project uses the simple permissive MIT license. In terms of what this mean practically, it's really nothing else than putting (e.g.) what is on https://choosealicense.com/licenses/mit/ into a LICENSE.txt file at the root of this repo! You can also add it to each .java source file, but having a single LICENSE.txt file in the repo would be great start. FYI GitHub will then show that in the top "bar" of the project, after 171 commits, 2 branches, 20 releases, 4 contributors.

**Comment by vorburger** [comment]
> In terms of what this mean practically, it's really nothing else than putting (...) into a LICENSE.txt file at the root of this repo!

e.g. like https://github.com/hsyyid/Inspector/pull/23 does for https://github.com/hsyyid/Inspector/issues/5

**Comment by Eufranio** [comment]
Did that, thanks!

**Comment by vorburger** [comment]
https://github.com/Eufranio/MagiBridge/commit/ee63e0afef3491b5b84b5eb264e6f8db0c44b88e
